import { Injectable, signal, computed, Inject, PLATFORM_ID } from '@angular/core';
import { isPlatformBrowser } from '@angular/common';
import { HttpClient } from '@angular/common/http';

export type Language = string;

@Injectable({ providedIn: 'root' })
export class LanguageService {
  private readonly storageKey = 'eco-lang';
  readonly currentLang = signal<Language>('en');
  readonly isRtl = computed(() => this.currentLang() === 'ar');
  readonly availableLanguages = signal<string[]>(['en', 'ar']);
  private readonly loadedTranslations: Record<string, Record<string, string>> = {};

  private readonly translations: Record<Language, Record<string, string>> = {
    en: {
      // Nav & Header
      'NAV_HOME': 'Home',
      'NAV_SHOP': 'Shop',
      'NAV_CATEGORIES': 'Categories',
      'NAV_BEST_SELLERS': 'Best Sellers',
      'NAV_ABOUT': 'About',
      'NAV_CONTACT': 'Contact',
      'NAV_CART': 'Cart',
      'NAV_WISHLIST': 'Wishlist',
      'NAV_NOTIFICATIONS': 'Notifications',
      'NOTIFICATIONS_EMPTY': 'You have no notifications.',
      'NOTIFICATIONS_CLEAR': 'Clear all',
      'NOTIFICATIONS_CLEAR_CONFIRM': 'Clear all notifications?',
      'NOTIFICATION_ORDER_CREATED_TITLE': 'Order created',
      'NOTIFICATION_ORDER_CREATED_MESSAGE': 'Your order #{id} was created successfully.',
      'NOTIFICATION_ORDER_STATUS_TITLE': 'Order status updated',
      'NOTIFICATION_ORDER_STATUS_MESSAGE': 'Your order #{id} is now {status}.',
      'NOTIFICATION_STATUS_PENDING': 'pending',
      'NOTIFICATION_STATUS_SHIPPED': 'shipped',
      'NOTIFICATION_STATUS_DELIVERED': 'delivered',
      'NOTIFICATION_STATUS_PAYMENT_RECEIVED': 'payment received',
      'NOTIFICATION_STATUS_PAYMENT_FAILED': 'payment failed',
      'NAV_ACCOUNT': 'Account',
      'NAV_PROFILE': 'Profile',
      'NAV_ADMIN_DASHBOARD': 'Admin Dashboard',
      'ACCOUNT_ADDRESS': 'Saved Address',
      'ACCOUNT_ADDRESS_SAVED': 'Saved',
      'ACCOUNT_EDIT_ADDRESS': 'Edit Address',
      'ACCOUNT_ADD_ADDRESS': 'Add Address',
      'ACCOUNT_ADDRESS_FIRST': 'First Name',
      'ACCOUNT_ADDRESS_LAST': 'Last Name',
      'ACCOUNT_ADDRESS_STREET': 'Street Address',
      'ACCOUNT_ADDRESS_CITY': 'City',
      'ACCOUNT_ADDRESS_STATE': 'State / Region',
      'ACCOUNT_ADDRESS_ZIP': 'ZIP Code',
      'ACCOUNT_ADDRESS_COUNTRY': 'Country',
      'ACCOUNT_ADDRESS_EMPTY': 'No address saved yet. Add one to speed up checkout.',
      'ACCOUNT_REQUIRED': 'This field is required',
      'ACCOUNT_ZIP_INVALID': 'Enter a valid ZIP code',
      'ACCOUNT_SAVE_ADDRESS': 'Save Address',
      'ACCOUNT_SAVING': 'Saving...',
      'ACCOUNT_CANCEL': 'Cancel',
      'DRAWER_NEW_ARRIVALS': 'New Arrivals',
      'AUTH_LOGIN_SUB_SHORT': 'Access your account',
      'AUTH_PANEL_TITLE': 'Shopping that feels premium.',
      'AUTH_PANEL_SUB': 'Join thousands of happy customers enjoying curated products, fast delivery and secure checkout.',
      'AUTH_PANEL_POINT_SECURE': 'SSL-encrypted secure checkout',
      'AUTH_PANEL_POINT_TRACK': 'Live order tracking',
      'AUTH_PANEL_POINT_PAY': 'Safe card payments via Stripe',
      'NAV_MY_ORDERS': 'My Orders',
      'NAV_LOGOUT': 'Logout',
      'NAV_MENU': 'Menu',
      'NAV_TOGGLE_MENU': 'Toggle menu',
      'NAV_MOBILE_NAV': 'Mobile navigation',
      'NAV_CLOSE_MENU': 'Close menu',
      'BRAND_TAGLINE': 'Premium Store',
      'ADMIN_DASHBOARD': 'Dashboard',
      'ADMIN_PRODUCTS': 'Products',
      'ADMIN_CATEGORIES': 'Categories',
      'ADMIN_ORDERS': 'Orders',
      'ADMIN_ORDERS_DESCRIPTION': 'Review orders, update their status and track fulfilment.',
      'ADMIN_FROM_DATE': 'From',
      'ADMIN_TO_DATE': 'To',
      'ADMIN_VIEW_ORDER': 'View order details',
      'ADMIN_CHANGE_STATUS': 'Change order status',
      'ADMIN_FILTER_STATUS': 'Filter by status',
      'ADMIN_ORDER_DETAILS': 'Order details',
      'ADMIN_INVOICE': 'Invoice',
      'ADMIN_PRINT_INVOICE': 'Print invoice',
      'ADMIN_CLOSE': 'Close',
      'ADMIN_LOADING_ORDER': 'Loading order details…',
      'ADMIN_DISCOUNT': 'Discount',
      'ADMIN_EMAIL': 'Email',
      'ADMIN_PHONE': 'Phone',
      'ADMIN_NOT_AVAILABLE': 'Not registered on the account',
      'ADMIN_ALL_STATUSES': 'All statuses',
      'ADMIN_PENDING': 'Pending',
      'ADMIN_PAID': 'Paid',
      'ADMIN_PAYMENT_FAILED': 'Payment failed',
      'ADMIN_SHIPPED': 'Shipped',
      'ADMIN_DELIVERED': 'Delivered',
      'ADMIN_SEARCH_ORDERS': 'Search by customer email…',
      'ADMIN_ORDERS_COUNT': 'orders',
      'ADMIN_DATE': 'Date',
      'ADMIN_PAYMENT': 'Payment',
      'ADMIN_DELIVERY': 'Delivery',
      'ADMIN_SHIPPING_ADDRESS': 'Shipping address',
      'ADMIN_SUBTOTAL': 'Subtotal',
      'ADMIN_SHIPPING': 'Shipping',
      'ADMIN_LOADING_ORDERS': 'Loading orders…',
      'ADMIN_NO_ORDERS_FOUND': 'No orders found.',
      'ADMIN_PAGE': 'Page',
      'ADMIN_OF': 'of',
      'ADMIN_CUSTOMERS': 'Customers',
      'ADMIN_COUPONS': 'Coupons',
      'ADMIN_LOCATIONS': 'Locations',
      'ADMIN_LANDING': 'Landing Pages',
      'ADMIN_WEBHOOKS': 'Webhooks',
      'ADMIN_SETTINGS': 'Settings',
      'ADMIN_EMAIL_SETTINGS': 'Email Design',
      'ADMIN_WEBHOOKS_TITLE': 'Outgoing Webhooks',
      'ADMIN_WEBHOOKS_DESCRIPTION': 'Send order and form events to an external service.',
      'ADMIN_WEBHOOK_ENDPOINT': 'Endpoint URL',
      'ADMIN_WEBHOOK_EVENTS': 'Subscribed events',
      'ADMIN_WEBHOOK_ORDER_CREATED': 'New order created',
      'ADMIN_WEBHOOK_FORM_STARTED': 'Form started',
      'ADMIN_WEBHOOK_ENABLED': 'Enable webhook delivery',
      'ADMIN_WEBHOOK_SAVE': 'Save webhook',
      'ADMIN_WEBHOOK_SAVING': 'Saving...',
      'ADMIN_WEBHOOK_SECRET_NOTICE': 'Copy this secret now. It will not be shown again.',
      'ADMIN_WEBHOOK_LOGS': 'Recent delivery attempts',
      'ADMIN_WEBHOOK_NO_LOGS': 'No delivery attempts yet.',
      'ADMIN_WEBHOOK_DELIVERED': 'Delivered',
      'ADMIN_WEBHOOK_FAILED': 'Failed',
      'ADMIN_WEBHOOK_ATTEMPT': 'Attempt',
      'ADMIN_WEBHOOK_VALIDATION': 'Enter a valid URL and select at least one event.',
      'ADMIN_MANAGE': 'Manage',
      'ADMIN_BACK_TO_STORE': 'Back to store',
      'ADMIN_LOG_OUT': 'Log out',
      'ADMIN_MENU': 'Menu',
      'ADMIN_LIVE_OVERVIEW': 'Live overview of your store performance.',
      'ADMIN_REFRESH': 'Refresh',
      'ADMIN_LOADING_DASHBOARD': 'Loading dashboard…',
      'ADMIN_DASHBOARD_LOAD_ERROR': 'Unable to load the dashboard. Try again.',
      'ADMIN_TOTAL_REVENUE': 'Total Revenue',
      'ADMIN_REGISTERED': 'registered',
      'ADMIN_AVG_ORDER': 'Avg. Order Value',
      'ADMIN_PRODUCTS_LIVE': 'products live',
      'ADMIN_SALES_7_DAYS': 'Sales — last 7 days',
      'ADMIN_THIS_WEEK': 'this week',
      'ADMIN_THIS_MONTH': 'this month',
      'ADMIN_RECENT_ORDERS': 'Recent orders',
      'ADMIN_VIEW_ALL': 'View all',
      'ADMIN_BEST_SELLERS': 'Best sellers',
      'ADMIN_LOW_STOCK': 'Low stock',
      'ADMIN_PRODUCTS_LINK': 'Products',
      'ADMIN_NO_ORDERS': 'No orders yet.',
      'ADMIN_NO_SALES': 'No sales data yet.',
      'ADMIN_STOCK_HINT': '5 or less remaining',
      'ADMIN_WELL_STOCKED': 'All products are well stocked.',
      'ADMIN_LOCATIONS_TITLE': 'Locations',
      'ADMIN_LOCATIONS_DESCRIPTION': 'Manage governorates and cities stored in the database. No JSON editing is needed.',
      'ADMIN_GOVERNORATES': 'Governorates',
      'ADMIN_ADD_GOVERNORATE': 'Add governorate',
      'ADMIN_ADD_GOVERNORATE_DESC': 'Add the English name, Arabic name, and a stable code.',
      'ADMIN_CODE': 'Code',
      'ADMIN_ENGLISH_NAME': 'English name',
      'ADMIN_ARABIC_NAME': 'Arabic name',
      'ADMIN_ADD_GOVERNORATE_BTN': 'Add governorate',
      'ADMIN_LOADING_LOCATIONS': 'Loading locations…',
      'ADMIN_DIRECTORY': 'Directory',
      'ADMIN_GOVERNORATES_AND_CITIES': 'Governorates and cities',
      'ADMIN_DELETE_GOVERNORATE': 'Delete governorate',
      'ADMIN_CITIES': 'Cities',
      'ADMIN_AVAILABLE_IN_CHECKOUT': 'Available in checkout',
      'ADMIN_ADD_CITY': 'Add city',
      'ADMIN_NO_GOVERNORATES': 'No governorates yet',
      'ADMIN_NO_GOVERNORATES_DESC': 'Add the first governorate above to start building the directory.',
      'ADMIN_LANDING_PAGES_TITLE': 'Landing Pages',
      'ADMIN_LANDING_PAGES_DESCRIPTION': 'Build professional one-page ads for your products and share the link anywhere.',
      'ADMIN_NEW_LANDING_PAGE': '+ New Landing Page',
      'ADMIN_LOADING_LANDING_PAGES': 'Loading landing pages…',
      'ADMIN_NO_LANDING_PAGES': 'No landing pages yet',
      'ADMIN_NO_LANDING_PAGES_DESC': 'Create your first product landing page and publish it with a shareable link.',
      'ADMIN_CREATE_LANDING_PAGE': 'Create one now',
      'ADMIN_TITLE': 'Title',
      'ADMIN_LINK': 'Link',
      'ADMIN_SECTIONS': 'Sections',
      'ADMIN_VIEWS': 'Views',
      'ADMIN_UPDATED': 'Updated',
      'ADMIN_SLUG': 'Slug',
      'ADMIN_PUBLISHED': 'Published',
      'ADMIN_DRAFT': 'Draft',
      'ADMIN_LAST_UPDATED': 'Last Updated',
      'ADMIN_VIEW_PAGE': 'View Page',
      'ADMIN_EDIT_PAGE': 'Edit Page',
      'ADMIN_EDIT_LANDING_PAGE': 'Edit Landing Page',
      'ADMIN_LANDING_PAGE_INTRO': 'Compose sections, link a product, then publish and share the link.',
      'ADMIN_SAVING': 'Saving…',
      'ADMIN_SAVE_LANDING_PAGE': 'Save Landing Page',
      'ADMIN_LOADING': 'Loading…',
      'ADMIN_LANDING_PAGE_FORM_INTRO': 'Give the page a name, choose the product it sells, then add only the sections you need.',
      'ADMIN_PAGE_TITLE': 'Page Title',
      'ADMIN_PAGE_TITLE_PLACEHOLDER': 'e.g. Eco Bottle Launch Offer',
      'ADMIN_SHARE_LINK_NAME': 'Share link name',
      'ADMIN_SLUG_PLACEHOLDER': 'eco-bottle-offer',
      'ADMIN_PRODUCT_TO_SELL': 'Product to sell',
      'ADMIN_OPTIONAL': 'optional',
      'ADMIN_NONE': '— None —',
      'ADMIN_PUBLISH_NOW': 'Publish now',
      'ADMIN_PUBLIC_LINK': 'Your public link',
      'ADMIN_PAGE_SECTIONS': 'Page sections',
      'ADMIN_ADD_BLOCKS_IN_ORDER': 'Add blocks in the order they should appear on the page.',
      'ADMIN_CHOOSE_BLOCK': 'Choose a block…',
      'ADMIN_ADD': '+ Add',
      'ADMIN_NO_SECTIONS_YET': 'No sections yet',
      'ADMIN_START_WITH_HERO': 'Start with a Hero section, then add features, reviews, FAQ and an order form.',
      'ADMIN_SECTION_LABEL_PLACEHOLDER': 'Section label (shown above the content)',
      'ADMIN_MOVE_UP': 'Move up',
      'ADMIN_MOVE_DOWN': 'Move down',
      'ADMIN_HIDE': 'Hide',
      'ADMIN_SHOW': 'Show',
      'ADMIN_REMOVE': 'Remove',
      'ADMIN_IMAGE_URL': 'Image URL',
      'ADMIN_IMAGE_URL_PLACEHOLDER': 'https://… or Images/Products/photo.jpg',
      'ADMIN_HEADLINE': 'Headline',
      'ADMIN_BODY_TEXT': 'Body text',
      'ADMIN_BUTTON_TEXT': 'Button text',
      'ADMIN_BUTTON_LINK': 'Button link',
      'ADMIN_BUTTON_LINK_PLACEHOLDER': 'e.g. #order',
      'ADMIN_ADD_ITEM': '+ Add item',
      'ADMIN_ICON': 'icon',
      'ADMIN_RATING': 'rating',
      'ADMIN_REVIEW': 'review',
      'ADMIN_QUESTION': 'question',
      'ADMIN_ANSWER': 'answer',
      'ADMIN_CUSTOMERS_TITLE': 'Customers',
      'ADMIN_CUSTOMERS_DESCRIPTION': 'Everyone registered in the store, their orders and admin access.',
      'ADMIN_SEARCH_CUSTOMERS_PLACEHOLDER': 'Search by name or email…',
      'ADMIN_CUSTOMER_FILTER': 'Filter by access',
      'ADMIN_CUSTOMER_FILTER_ALL': 'All customers',
      'ADMIN_CUSTOMER_FILTER_CUSTOMERS': 'Customers only',
      'ADMIN_CUSTOMER_FILTER_ADMINS': 'Admins only',
      'ADMIN_CUSTOMERS_COUNT': 'customers',
      'ADMIN_TOTAL_SPENT': 'Total spent',
      'ADMIN_VIEW': 'View',
      'ADMIN_ROLES': 'Roles',
      'ADMIN_CUSTOMER_ROLE': 'Customer',
      'ADMIN_ADMIN_ROLE': 'Admin',
      'ADMIN_REMOVE_ADMIN': 'Remove admin',
      'ADMIN_MAKE_ADMIN': 'Make admin',
      'ADMIN_NO_CUSTOMERS_FOUND': 'No customers found.',
      'ADMIN_LOADING_CUSTOMER': 'Loading customer…',
      'ADMIN_SPENT': 'spent',
      'ADMIN_CUSTOMER_NO_ORDERS': 'This customer has no orders yet.',
      'ADMIN_COUPONS_TITLE': 'Coupons',
      'ADMIN_COUPONS_DESCRIPTION': 'Create discount coupons your customers can apply in the basket.',
      'ADMIN_NEW_COUPON': '+ New Coupon',
      'ADMIN_EDIT_COUPON': 'Edit coupon',
      'ADMIN_COUPON_CODE': 'Code',
      'ADMIN_COUPON_TYPE': 'Type',
      'ADMIN_COUPON_PERCENTAGE': 'Percentage (%)',
      'ADMIN_COUPON_FIXED_AMOUNT': 'Fixed amount ($)',
      'ADMIN_COUPON_VALUE': 'Value',
      'ADMIN_COUPON_EXPIRY_DATE': 'Expiry date',
      'ADMIN_COUPON_MAX_USES': 'Max uses',
      'ADMIN_COUPON_ACTIVE': 'Active',
      'ADMIN_SAVE_COUPON': 'Save coupon',
      'ADMIN_ALL_COUPONS': 'All coupons',
      'ADMIN_USAGE': 'Usage',
      'ADMIN_EXPIRY': 'Expiry',
      'ADMIN_COUPON_INACTIVE': 'Inactive',
      'ADMIN_COUPON_EXPIRED': 'Expired',
      'ADMIN_NO_COUPONS_YET': 'No coupons yet. Create your first one!',
      'ADMIN_EDIT_CATEGORY': 'Edit category',
      'ADMIN_CATEGORY_NAME_PLACEHOLDER': 'e.g. Home & Living',
      'ADMIN_CATEGORY_DESCRIPTION_PLACEHOLDER': 'Add a short description for this category',
      'ADMIN_SAVE_CHANGES': 'Save changes',
      'ADMIN_ADD_CATEGORY': 'Add category',
      'ADMIN_SEARCH_CATEGORIES': 'Search categories',
      'ADMIN_SEARCH_CATEGORIES_PLACEHOLDER': 'Search categories…',
      'ADMIN_NO_PAID_ORDERS_7_DAYS': 'No paid orders in the last 7 days — revenue will appear here as orders come in.',
      'ADMIN_SOLD': 'sold',
      'ADMIN_LEFT': 'left',
      'ADMIN_DASH': '—',
      'ADMIN_COUPON': 'coupon',
      'ADMIN_NAME': 'Name',
      'ADMIN_DESCRIPTION': 'Description',
      'ADMIN_NEW_CATEGORY': 'New category',
      'ADMIN_NAME_REQUIRED': 'Name is required.',
      'ADMIN_DESCRIPTION_REQUIRED': 'Description is required.',
      'ADMIN_LOADING_CATEGORIES': 'Loading categories…',
      'ADMIN_NO_CATEGORIES': 'No categories found.',
      'ADMIN_ORDER': 'Order',
      'ADMIN_CUSTOMER': 'Customer',
      'ADMIN_ITEMS': 'Items',
      'ADMIN_STATUS': 'Status',
      'ADMIN_TOTAL': 'Total',

      // About
      'ABOUT_EYEBROW': 'About Eco',
      'ABOUT_TITLE': 'Thoughtful products for everyday life.',
      'ABOUT_INTRO': 'Eco is a premium storefront built around carefully selected products and a simple, joyful shopping experience. We believe great design and quality should be accessible to everyone.',
      'ABOUT_SHOP_CTA': 'Explore the Shop',
      'ABOUT_VALUES_EYEBROW': 'What we stand for',
      'ABOUT_VALUES_TITLE': 'Our values',
      'ABOUT_VALUE_QUALITY_TITLE': 'Quality First',
      'ABOUT_VALUE_QUALITY_DESC': 'Every product is hand-picked and vetted for durability, design, and real-world value.',
      'ABOUT_VALUE_SUSTAINABILITY_TITLE': 'Sustainability',
      'ABOUT_VALUE_SUSTAINABILITY_DESC': 'We partner with brands that share our commitment to responsible sourcing and packaging.',
      'ABOUT_VALUE_CUSTOMER_TITLE': 'Customer Focus',
      'ABOUT_VALUE_CUSTOMER_DESC': 'Your satisfaction is our priority. We offer easy returns and round-the-clock support.',
      'ABOUT_VALUE_PRICING_TITLE': 'Fair Pricing',
      'ABOUT_VALUE_PRICING_DESC': 'Premium quality does not have to mean premium prices. We work hard to keep things affordable.',

      // Shop & Items
      'SHOP_ADD_TO_CART': 'Add to Cart',
      'SHOP_VIEW_DETAILS': 'View details',
      'SHOP_PREMIUM_PICKS': 'Premium Picks',
      'SHOP_ALL_PRODUCTS': 'All Products',
      'SHOP_FEATURED': 'Featured Items',
      'SHOP_NO_PRODUCTS': 'No Products Found',
      'SHOP_NO_PRODUCTS_DESC': 'There are currently no products available to display.',
      'SHOP_REFRESH': 'Refresh Products',
      'SHOP_EYEBROW': 'Curated for everyday life',
      'SHOP_TITLE': 'Find your next favorite',
      'SHOP_INTRO': 'Discover quality products, thoughtfully selected for you.',
      'SHOP_PRODUCTS_AVAILABLE': 'Products Available',
      'BS_EYEBROW': 'Curated High-End Selection',
      'BS_TITLE': 'Premium Picks',
      'BS_INTRO': 'Explore top-tier selections from the Eco catalog, chosen for exceptional quality and craftsmanship.',
      'BS_FEATURED_COUNT': 'Featured Items',
      'BS_UPDATING': 'Updating products...',
      'BS_NO_PRODUCTS': 'No Products Found',
      'BS_NO_PRODUCTS_DESC': 'There are currently no products available to display.',

      // Checkout payment methods
      'CHECKOUT_PAYMENT_METHOD': 'Payment Method',
      'CHECKOUT_PAY_STRIPE': 'Card (Visa)',
      'CHECKOUT_PAY_STRIPE_DESC': 'Secure credit/debit card payment',
      'CHECKOUT_PAY_INSTAPAY': 'InstaPay',
      'CHECKOUT_PAY_INSTAPAY_DESC': 'Instant bank or wallet transfer',
      'CHECKOUT_PAY_VODAFONE': 'Vodafone Cash',
      'CHECKOUT_PAY_VODAFONE_DESC': 'Pay from your Vodafone wallet',
      'CHECKOUT_PAY_COD': 'Cash on Delivery',
      'CHECKOUT_PAY_COD_DESC': 'Pay cash when your order arrives',
      'CHECKOUT_PAY_UNAVAILABLE': 'Unavailable',
      'CHECKOUT_WALLET_INSTRUCTIONS': 'Transfer the order total to 0100 990 1702, then send us the receipt on WhatsApp to confirm your order.',
      'CHECKOUT_WALLET_INSTRUCTIONS_PREFIX': 'Transfer the order total to',
      'CHECKOUT_WALLET_INSTRUCTIONS_SUFFIX': ', then send us the receipt on WhatsApp to confirm your order.',
      'CHECKOUT_COD_INSTRUCTIONS': 'Pay in cash to the courier when your order is delivered.',

      // Auth social + shipping
      'AUTH_GOOGLE': 'Continue with Google',
      'AUTH_OR': 'or',
      'BASKET_SHIPPING_FROM': 'from',

      // Wishlist
      'WISHLIST_EYEBROW': 'Saved For Later',
      'WISHLIST_TITLE': 'My Wishlist',
      'WISHLIST_INTRO': 'All the products you loved, saved in one place and ready when you are.',
      'WISHLIST_COUNT': 'Saved Items',
      'WISHLIST_SIGNIN_TITLE': 'Sign in to see your wishlist',
      'WISHLIST_SIGNIN_DESC': 'Your wishlist is tied to your account, so your saved items follow you across devices.',
      'WISHLIST_SIGNIN_CTA': 'Sign In',
      'WISHLIST_EMPTY_TITLE': 'Your wishlist is empty',
      'WISHLIST_EMPTY_DESC': 'Tap the heart on any product to save it here for later.',
      'WISHLIST_EMPTY_CTA': 'Browse the Shop',
      'BS_REFRESH': 'Refresh Products',
      'SHOP_TOGGLE_FILTERS': 'Toggle filters',
      'SHOP_FILTERS_SORTING': 'Filters & Sorting',
      'SHOP_OPEN': 'Open',
      'SHOP_CLOSE': 'Close',
      'SHOP_BROWSE': 'Browse',
      'SHOP_SORTING': 'Sorting',
      'SHOP_SORT_PRODUCTS': 'Sort products',
      'SHOP_SORT_NAME': 'Name',
      'SHOP_SORT_PRICE_ASC': 'Price: Min to Max',
      'SHOP_SORT_PRICE_DESC': 'Price: Max to Min',
      'SHOP_ALL': 'All',
      'SHOP_SEARCH': 'Search',
      'SHOP_SEARCH_PLACEHOLDER': 'Search products...',
      'SHOP_RESET_FILTERS': 'Reset filters',
      'SHOP_OF': 'of',
      'SHOP_PRODUCTS': 'products',
      'SHOP_UPDATING': 'Updating products...',
      'SHOP_PAGINATION': 'Product pagination',
      'SHOP_PRODUCT_RATING': 'Product rating',
      'SHOP_NO_REVIEWS': '0.0 (0)',
      'PRODUCT_IN_STOCK': 'In Stock',
      'PRODUCT_REVIEWS': 'customer reviews',
      'PRODUCT_SAVE': 'Save',
      'PRODUCT_DISCOUNT': 'OFF',
      'PRODUCT_ADD_TO_BASKET': 'Add to Basket',
      'PRODUCT_ADDED_TO_BASKET': 'Added to Basket',
      'PRODUCT_DESCRIPTION': 'Description',
      'PRODUCT_REVIEWS_TAB': 'Reviews',
      'PRODUCT_OVERVIEW': 'Product Overview',
      'PRODUCT_SPECIFICATIONS': 'Product specifications',
      'PRODUCT_PERK_1': 'Premium grade craftsmanship built for everyday longevity.',
      'PRODUCT_PERK_2': 'Thoroughly tested for optimal energy and performance efficiency.',
      'PRODUCT_PERK_3': 'Includes all standard accessories and documentation in box.',
      'PRODUCT_BASED_ON_REVIEWS': 'Based on reviews',
      'PRODUCT_NO_REVIEWS_YET': 'No reviews yet — be the first to write one!',
      'PRODUCT_WRITE_REVIEW': 'Write a Review',
      'PRODUCT_CANCEL_REVIEW': 'Cancel Review',
      'PRODUCT_LEAVE_REVIEW': 'Leave your review',
      'PRODUCT_OVERALL_RATING': 'Your Overall Rating:',
      'PRODUCT_OUT_OF_STARS': 'out of 5 Stars',
      'PRODUCT_REVIEWING_AS': 'Reviewing as',
      'PRODUCT_REVIEW_HEADLINE': 'Review Headline',
      'PRODUCT_REVIEW_TITLE_PLACEHOLDER': 'e.g. Exceptional quality and easy to use!',
      'PRODUCT_REVIEW_EXPERIENCE': 'Your Review & Experience *',
      'PRODUCT_REVIEW_PLACEHOLDER': 'Share your thoughts about this product quality, features, and experience...',
      'PRODUCT_SUBMITTING_REVIEW': 'Submitting…',
      'PRODUCT_SUBMIT_REVIEW': 'Submit Review',
      'PRODUCT_CUSTOMER_FEEDBACK': 'Customer Feedback',
      'PRODUCT_LOADING_REVIEWS': 'Loading reviews…',
      'PRODUCT_NO_REVIEWS': 'No reviews yet',
      'PRODUCT_FIRST_REVIEW': 'Be the first to share your experience with this product.',
      'PRODUCT_LOAD_ERROR': 'Unable to load product',
      'PRODUCT_NOT_FOUND': 'Product not found',
      'PRODUCT_NOT_FOUND_DESC': "The product you're looking for doesn't exist or is currently unavailable.",
      'PRODUCT_BROWSE_ALL': 'Browse All Products',
      'ADMIN_PRODUCT_NEW': 'New product',
      'ADMIN_PRODUCT_EDIT': 'Edit product',
      'ADMIN_PRODUCT_NAME': 'Name',
      'ADMIN_PRODUCT_CATEGORY': 'Category',
      'ADMIN_PRODUCT_SELECT_CATEGORY': 'Select a category',
      'ADMIN_PRODUCT_CURRENT_PRICE': 'Current price',
      'ADMIN_PRODUCT_ORIGINAL_PRICE': 'Original price',
      'ADMIN_PRODUCT_DESCRIPTION': 'Description',
      'ADMIN_PRODUCT_IMAGES': 'Images',
      'ADMIN_PRODUCT_CREATE': 'Create product',
      'ADMIN_PRODUCT_TRACK_STOCK': 'Track inventory',
      'ADMIN_PRODUCT_QUANTITY': 'Available quantity',
      'ADMIN_PRODUCT_PACKAGE_DETAILS': 'Package details',
      'ADMIN_PRODUCT_OPTIONAL': 'Optional',
      'ADMIN_PRODUCT_LENGTH': 'Length',
      'ADMIN_PRODUCT_WIDTH': 'Width',
      'ADMIN_PRODUCT_HEIGHT': 'Height',
      'ADMIN_PRODUCT_WEIGHT': 'Weight',
      'ADMIN_PRODUCT_MORE_SPECS': 'Additional specifications',
      'ADMIN_PRODUCT_CHOOSE_IMAGES': 'Choose images',
      'ADMIN_PRODUCT_IMAGE_TYPES': 'PNG, JPG or WEBP',
      'ADMIN_PRODUCT_DROP_IMAGES': 'or drag images here',
      'ADMIN_PRODUCT_PREVIEW_COUNT': 'preview(s)',
      'ADMIN_PRODUCTS_DESCRIPTION': 'Create, edit and remove catalog products.',
      'ADMIN_CLOSE_FORM': 'Close form',
      'ADMIN_PRODUCT_NEW_ACTION': '+ New product',
      'ADMIN_ALL_PRODUCTS': 'All products',
      'ADMIN_SEARCH_PRODUCTS': 'Search by name…',
      'ADMIN_ALL_CATEGORIES': 'All categories',
      'ADMIN_PRODUCT': 'Product',
      'ADMIN_CATEGORY': 'Category',
      'ADMIN_PRICE': 'Price',
      'ADMIN_STOCK': 'Stock',
      'ADMIN_ACTIONS': 'Actions',
      'ADMIN_LOADING_PRODUCTS': 'Loading products…',
      'ADMIN_NO_PRODUCTS': 'No products found.',
      'ADMIN_NOT_TRACKED': 'Not tracked',
      'ADMIN_DELETE': 'Delete',
      'ADMIN_CANCEL': 'Cancel',
      'ADMIN_PRODUCT_NAME_REQUIRED': 'Name is required.',
      'ADMIN_PRODUCT_NAME_PLACEHOLDER': 'e.g. Ceramic espresso machine',
      'ADMIN_PRODUCT_CATEGORY_REQUIRED': 'Please pick a category.',
      'ADMIN_PRODUCT_PRICE_REQUIRED': 'Current price is required.',
      'ADMIN_PRODUCT_DESCRIPTION_REQUIRED': 'Description is required.',
      'ADMIN_PRODUCT_DESCRIPTION_PLACEHOLDER': 'Describe the product in a few words…',
      'ADMIN_PRODUCT_SPECIFICATIONS_JSON': 'Specifications (JSON)',
      'ADMIN_PRODUCT_SPECS_HINT': 'Optional technical details for the product page.',
      'ADMIN_PRODUCT_SPECS_PLACEHOLDER': '[{"label":"Capacity","value":"1.5 L"}]',
      'ADMIN_PRODUCT_SPECS_FORMAT': 'Add each specification as a label and value.',
      'ADMIN_PRODUCT_REPLACE_IMAGES': '(optional; replaces existing)',
      'ADMIN_PRODUCT_IMAGE_REQUIRED': 'At least one image is required for a new product.',
      'ADMIN_PRODUCT_SAVING': 'Saving…',
      'ADMIN_PRODUCT_SAVE_CHANGES': 'Save changes',
      'ADMIN_PRODUCTS_LOAD_ERROR': 'Could not load products.',
      'ADMIN_PRODUCT_FORM_ERROR': 'Please fill in the highlighted fields.',
      'ADMIN_PRODUCT_STOCK_REQUIRED': 'Enter the available quantity or turn off inventory tracking.',
      'ADMIN_PRODUCT_SPECS_ERROR': 'Specifications must be a valid JSON array with label and value.',
      'ADMIN_PRODUCT_CREATED': 'Product created.',
      'ADMIN_PRODUCT_UPDATED': 'Product updated.',
      'ADMIN_PRODUCT_SAVE_ERROR': 'Could not save the product.',
      'ADMIN_PRODUCT_DELETE_CONFIRM': 'Delete this product? This cannot be undone.',
      'ADMIN_PRODUCT_DELETED': 'Product deleted.',
      'ADMIN_PRODUCT_DELETE_ERROR': 'Could not delete the product.',
      'WISHLIST_ADD': 'Add to wishlist',
      'WISHLIST_REMOVE': 'Remove from wishlist',

      // Home
      'HOME_WELCOME': 'Welcome',
      'HOME_HERO_TITLE': 'Better products for everyday living.',
      'HOME_HERO_SUBTITLE': 'Discover thoughtfully selected essentials with a premium shopping experience made for you.',
      'HOME_SHOP_NOW': 'Shop now',
      'HOME_BRANDS': 'Brands',
      'HOME_RATING': 'Rating',
      'HOME_SHOP_BY_NEED': 'Shop by need',
      'HOME_FEATURED_CATEGORIES': 'Featured categories',
      'HOME_VIEW_ALL': 'View all',
      'HOME_CAREFULLY_SELECTED': 'Carefully selected',
      'HOME_SHOP_ALL': 'Shop all',
      'HOME_ECO_COLLECTION': 'Eco collection',
      'HOME_FREE_SHIPPING': 'Free Shipping',
      'HOME_FREE_SHIPPING_DESC': 'On all orders over $50. Fast and reliable delivery to your door.',
      'HOME_EASY_RETURNS': 'Easy Returns',
      'HOME_EASY_RETURNS_DESC': '30-day hassle-free return policy. No questions asked.',
      'HOME_SECURE_PAYMENT': 'Secure Payment',
      'HOME_SECURE_PAYMENT_DESC': 'Your payment info is encrypted and always protected.',
      'HOME_SUPPORT': '24/7 Support',
      'HOME_SUPPORT_DESC': 'Our team is here for you any time, any day of the week.',
      'HOME_READY': 'Ready to shop?',
      'HOME_CTA_TITLE': 'Find your next favorite product today.',
      'HOME_CTA_DESC': 'Browse hundreds of curated, premium products at unbeatable prices.',

      // Account
      'ACCOUNT_LOADING': 'Loading your account details...',
      'ACCOUNT_MEMBER': 'Eco Member',
      'ACCOUNT_VALUED_CUSTOMER': 'Valued Customer',
      'ACCOUNT_SHOP_MORE': 'Shop More',
      'ACCOUNT_PROFILE': 'Profile Information',
      'ACCOUNT_ORDER_HISTORY': 'Order History',
      'ACCOUNT_DETAILS': 'Account Details',
      'ACCOUNT_DISPLAY_NAME': 'Display Name',
      'ACCOUNT_NOT_SPECIFIED': 'Not specified',
      'ACCOUNT_STATUS': 'Account Status',
      'ACCOUNT_ACTIVE_VERIFIED': 'Active & Verified',
      'ACCOUNT_MEMBERSHIP': 'Eco Membership',
      'ACCOUNT_STANDARD_MEMBER': 'Standard Member',
      'ACCOUNT_PROTECTED': 'Account Protected',
      'ACCOUNT_PROTECTED_DESC': 'Your session is encrypted and authenticated with secure cookie credentials.',
      'ACCOUNT_YOUR_ORDERS': 'Your Orders',
      'ACCOUNT_REFRESH': 'Refresh',
      'ACCOUNT_LOADING_ORDERS': 'Fetching your order history...',
      'ACCOUNT_NO_ORDERS': 'No orders placed yet',
      'ACCOUNT_NO_ORDERS_DESC': 'When you complete a purchase, your order history and tracking details will appear here.',
      'ACCOUNT_ORDER': 'Order',
      'ACCOUNT_TOTAL_AMOUNT': 'Total Amount',
      'ACCOUNT_ITEMS_COUNT': 'Items Count',
      'ACCOUNT_NEED_TRACKING': 'Need tracking details?',
      'ACCOUNT_TRACK_ORDER': 'Track Order',
      'ACCOUNT_WELCOME': 'Welcome to Your Account',
      'ACCOUNT_WELCOME_DESC': 'Sign in to view your orders, manage account settings, and enjoy a seamless checkout experience.',

      // Basket
      'BASKET_TITLE': 'Shopping Basket',
      'BASKET_EYEBROW': 'Your Cart',
      'BASKET_ITEM': 'item in your cart',
      'BASKET_ITEMS': 'items in your cart',
      'BASKET_CLEAR': 'Clear Cart',
      'BASKET_ITEMS_LABEL': 'Cart items',
      'BASKET_QUANTITY_FOR': 'Quantity for',
      'BASKET_DECREASE': 'Decrease quantity',
      'BASKET_INCREASE': 'Increase quantity',
      'BASKET_REMOVE': 'Remove',
      'BASKET_EACH': 'each',
      'BASKET_CONTINUE': 'Continue Shopping',
      'BASKET_SUMMARY': 'Order Summary',
      'BASKET_SUBTOTAL': 'Subtotal',
      'BASKET_SHIPPING': 'Shipping',
      'BASKET_FREE': 'FREE',
      'BASKET_FREE_SHIPPING_MSG': 'Add {amount} more for FREE shipping!',
      'BASKET_TOTAL': 'Total',
      'BASKET_CHECKOUT': 'Proceed to Checkout',
      'BASKET_EMPTY_TITLE': 'Your basket is empty',
      'BASKET_EMPTY_SUB': "Looks like you haven't added anything to your cart yet. Explore our curated catalog to discover great essentials.",
      'BASKET_EXPLORE': 'Explore the Shop',
      'BASKET_TRUST_SSL': 'SSL Encrypted & Secure Checkout',
      'BASKET_TRUST_FAST': 'Fast & Reliable Delivery',
      'BASKET_TRUST_PAY': 'Multiple Payment Methods',

      // Checkout
      'CHECKOUT_EYEBROW': 'Secure Checkout',
      'CHECKOUT_TITLE': 'Complete Your Order',
      'CHECKOUT_ORDER_PREVIEW_EYEBROW': 'Your selection',
      'CHECKOUT_ORDER_PREVIEW': 'Items in your order',
      'CHECKOUT_ITEMS': 'items',
      'CHECKOUT_QUANTITY': 'Qty',
      'CHECKOUT_EMPTY_ORDER': 'Your basket is empty.',
      'CHECKOUT_BACK': 'Back to Basket',
      'CHECKOUT_STEP_SHIPPING': 'Shipping Address',
      'CHECKOUT_STEP_SHIPPING_SUB': 'Where should we deliver your order?',
      'CHECKOUT_FIRST_NAME': 'First Name',
      'CHECKOUT_LAST_NAME': 'Last Name',
      'CHECKOUT_STREET': 'Street Address',
      'CHECKOUT_CITY': 'City',
      'CHECKOUT_STATE': 'State / Region',
      'CHECKOUT_SELECT_CITY': 'Select a city',
      'CHECKOUT_SELECT_STATE': 'Select a state',
      'CHECKOUT_SELECT_STATE_FIRST': 'Select a state first',
      'CHECKOUT_ZIP': 'ZIP / Postal Code',
      'CHECKOUT_STEP_DELIVERY': 'Delivery Method',
      'CHECKOUT_STEP_DELIVERY_SUB': 'Choose how fast you want your order',
      'CHECKOUT_CITY_DELIVERY': 'Delivery to your city',
      'CHECKOUT_BUSINESS_DAY': 'business day',
      'CHECKOUT_BUSINESS_DAYS': 'business days',
      'CHECKOUT_SAVING_ADDRESS': 'Saving address...',
      'CHECKOUT_UNAVAILABLE': 'Shipping is unavailable for this city',
      'CHECKOUT_PLACE_ORDER': 'Place Order Securely',
      'CHECKOUT_PLACING': 'Placing Order...',
      'CHECKOUT_FIRST_NAME_ERROR': 'First name is required (letters only, min. 2 chars)',
      'CHECKOUT_LAST_NAME_ERROR': 'Last name is required (letters only, min. 2 chars)',
      'CHECKOUT_STREET_ERROR': 'Street address is required (min. 5 chars)',
      'CHECKOUT_CITY_ERROR': 'City is required',
      'CHECKOUT_STATE_ERROR': 'State is required',
      'CHECKOUT_ZIP_ERROR': 'Valid ZIP code is required (4-10 digits)',
      'CHECKOUT_SAVED_ADDRESS_INVALID': 'Your saved address location is not available for shipping. Please select a new address.',
      'CHECKOUT_SAVED_CITY_INVALID': 'Your saved address city is not available for shipping. Please select a new city.',
      'CHECKOUT_LOADING_DELIVERY': 'Loading delivery options...',
      'CHECKOUT_DELIVERY': 'Delivery',
      'CHECKOUT_LEGAL_PREFIX': 'By placing your order you agree to our',
      'CHECKOUT_TERMS': 'Terms of Service',
      'CHECKOUT_LEGAL_AND': 'and',
      'CHECKOUT_STEP_PAYMENT': 'Payment',
      'CHECKOUT_STEP_PAYMENT_SUB': 'Pay securely with your credit or debit card',
      'CHECKOUT_NEXT': 'Continue',
      'CHECKOUT_STEP_BACK': 'Back',
      'CHECKOUT_EDIT': 'Edit',
      'CHECKOUT_REVIEW_NOTE': 'Your order is ready. Review the summary, then place your order securely.',
      'CHECKOUT_LOADING_PAYMENT': 'Loading secure payment form...',
      'CHECKOUT_PAYMENT_SECURE': 'Your card details are encrypted and processed securely.',

      // Order Tracking
      'ORDER_TRACKING_TITLE': 'Order Tracking',
      'ORDER_STEP_PLACED': 'Order Placed',
      'ORDER_STEP_PAYMENT': 'Payment Confirmed',
      'ORDER_STEP_SHIPPED': 'Shipped',
      'ORDER_STEP_DELIVERED': 'Delivered',
      'ORDER_BACK_LIST': 'Back to Orders',
      'ORDER_LOADING': 'Loading order details...',
      'ORDER_ERROR': 'Could not load order details.',
      'ORDER_SHIPPING_ADDRESS': 'Shipping Address',
      'ORDER_SUBTOTAL': 'Subtotal',
      'ORDER_DELIVERY': 'Delivery',
      'ORDER_TOTAL': 'Total',
      'ORDER_QR_TITLE': 'Scan to track this order',
      'ORDER_QR_ALT': 'QR code for order tracking',
      'ORDER_QR_HINT': 'Scan this code with your phone to open the order tracking page.',
      'ORDER_QTY': 'Qty',

      // Auth
      'AUTH_WELCOME_BACK': 'Welcome Back',
      'AUTH_LOGIN_SUB': 'Please enter your details to sign in to your account',
      'AUTH_CREATE_ACC': 'Create Account',
      'AUTH_REGISTER_SUB': 'Join Eco to enjoy seamless shopping and exclusive rewards',
      'AUTH_NAME': 'Full Name / Username',
      'AUTH_EMAIL': 'Email Address',
      'AUTH_PASSWORD': 'Password',
      'AUTH_FORGOT_PASS': 'Forgot password?',
      'AUTH_SIGN_IN': 'Sign In',
      'AUTH_SIGNING_IN': 'Signing in...',
      'AUTH_CREATING_ACC': 'Creating account...',
      'AUTH_NO_ACC': "Don't have an account?",
      'AUTH_HAVE_ACC': 'Already have an account?',
      'AUTH_REGISTER_LINK': 'Create account',
      'AUTH_LOGIN_LINK': 'Sign in',
      'AUTH_VALID_EMAIL': 'Please enter a valid email address.',
      'AUTH_PASSWORD_PLACEHOLDER': 'Enter your password',
      'AUTH_SHOW_PASSWORD': 'Show password',
      'AUTH_HIDE_PASSWORD': 'Hide password',
      'AUTH_PASSWORD_REQUIRED': 'Password is required.',
      'AUTH_NAME_PLACEHOLDER': 'e.g. John Doe',
      'AUTH_NAME_ERROR': 'Username must be at least 3 characters.',
      'AUTH_PASSWORD_MIN': 'At least 6 characters',
      'AUTH_PASSWORD_MIN_ERROR': 'Password must be at least 6 characters.',
      'AUTH_TOAST_GOOGLE_NOT_CONFIGURED': 'Google sign-in is not configured yet.',
      'AUTH_TOAST_GOOGLE_ERROR': 'Could not sign in with Google. Please try again.',
      'AUTH_TOAST_GOOGLE_TITLE': 'Google',
      'AUTH_TOAST_EMAIL_NOT_CONFIRMED': 'Please confirm your email before signing in.',
      'AUTH_TOAST_EMAIL_NOT_CONFIRMED_TITLE': 'Email not confirmed',
      'AUTH_TOAST_LOGIN_SUCCESS': 'Welcome back!',
      'AUTH_TOAST_LOGIN_FAILED': 'Login Failed',
      'AUTH_TOAST_SESSION_ERROR': 'Login succeeded, but the session could not be loaded. Please try again.',
      'AUTH_TOAST_INVALID_CREDENTIALS': 'Invalid email or password.',
      'AUTH_RECOVERY_EYEBROW': 'Account Recovery',
      'AUTH_RECOVERY_TITLE': 'Reset Your Password',
      'AUTH_RECOVERY_SUB': "Enter the email address associated with your Eco account and we'll send you a password recovery link.",
      'AUTH_RECOVERY_EMAIL': 'Email Address',
      'AUTH_RECOVERY_SEND': 'Send Reset Link',
      'AUTH_RECOVERY_SENDING': 'Sending Link...',
      'AUTH_RECOVERY_RETURN': 'Return to Sign In',
      'AUTH_RECOVERY_CHECK_INBOX': 'Check Your Inbox',
      'AUTH_RECOVERY_SENT_TITLE': 'Instructions Sent',
      'AUTH_RECOVERY_SENT_MESSAGE': 'If an account exists with that email address, we have sent instructions to reset your password. Please check your inbox and spam folder.',
      'AUTH_RECOVERY_INVALID_EMAIL': 'Please enter a valid email address.',
      'ADMIN_SHIPPING_PRICE': 'Shipping price',
      'ADMIN_DELIVERY_DAYS': 'Delivery days',
      'ADMIN_SHIPPING_AVAILABLE': 'Shipping available',
      'ADMIN_SHIPPING_UNAVAILABLE': 'Shipping unavailable',
      'ADMIN_SAVE_CITY': 'Save city',
      'ADMIN_EDIT': 'Edit',

      // Footer
      'FOOTER_SLOGAN': 'Curated premium products for modern living.',
      'FOOTER_SHOP': 'Shop',
      'FOOTER_SUPPORT': 'Support',
      'FOOTER_COMPANY': 'Company',
      'FOOTER_RIGHTS': 'All rights reserved.',
      'FOOTER_CRAFTED': 'Crafted with care',
      'FOOTER_ALL_PRODUCTS': 'All Products',
      'FOOTER_NEW_ARRIVALS': 'New Arrivals',
      'FOOTER_SHIPPING': 'Shipping',
      'FOOTER_RETURNS': 'Returns',
      'FOOTER_CAREERS': 'Careers',
      'FOOTER_PRIVACY': 'Privacy Policy'
      ,'FOOTER_CONTACT': 'Contact us'
      ,'FOOTER_HOURS': 'Saturday - Thursday, 9 AM - 9 PM'
      ,'FOOTER_FEATURE_QUALITY': 'Quality products'
      ,'FOOTER_FEATURE_QUALITY_SUB': 'Carefully selected for you'
      ,'FOOTER_FEATURE_NATURAL': 'Trusted selection'
      ,'FOOTER_FEATURE_NATURAL_SUB': 'From reliable sources'
      ,'FOOTER_FEATURE_DELIVERY': 'Fast, secure delivery'
      ,'FOOTER_FEATURE_DELIVERY_SUB': 'To your doorstep'
      ,'FOOTER_PAYMENT_METHODS': 'Payment methods'
      ,'FOOTER_PAYMENT_SECURE': 'Secure and trusted checkout'
    },
    ar: {
      // Nav & Header
      'NAV_HOME': 'الرئيسية',
      'NAV_SHOP': 'المتجر',
      'NAV_CATEGORIES': 'الأقسام',
      'NAV_BEST_SELLERS': 'الأكثر طلباً',
      'NAV_ABOUT': 'من نحن',
      'NAV_CONTACT': 'اتصل بنا',
      'NAV_CART': 'السلة',
      'NAV_WISHLIST': 'المفضلة',
      'NAV_NOTIFICATIONS': 'الإشعارات',
      'NOTIFICATIONS_EMPTY': 'لا توجد إشعارات حاليًا.',
      'NOTIFICATIONS_CLEAR': 'مسح الكل',
      'NOTIFICATIONS_CLEAR_CONFIRM': 'هل تريد مسح كل الإشعارات؟',
      'NOTIFICATION_ORDER_CREATED_TITLE': 'تم إنشاء الطلب',
      'NOTIFICATION_ORDER_CREATED_MESSAGE': 'تم إنشاء طلبك رقم {id} بنجاح.',
      'NOTIFICATION_ORDER_STATUS_TITLE': 'تم تحديث حالة الطلب',
      'NOTIFICATION_ORDER_STATUS_MESSAGE': 'حالة طلبك رقم {id} الآن: {status}.',
      'NOTIFICATION_STATUS_PENDING': 'قيد الانتظار',
      'NOTIFICATION_STATUS_SHIPPED': 'تم الشحن',
      'NOTIFICATION_STATUS_DELIVERED': 'تم التسليم',
      'NOTIFICATION_STATUS_PAYMENT_RECEIVED': 'تم استلام الدفع',
      'NOTIFICATION_STATUS_PAYMENT_FAILED': 'فشل الدفع',
      'NAV_ACCOUNT': 'حسابي',
      'NAV_PROFILE': 'الملف الشخصي',
      'NAV_ADMIN_DASHBOARD': 'لوحة تحكم الأدمن',
      'ACCOUNT_ADDRESS': 'العنوان المحفوظ',
      'ACCOUNT_ADDRESS_SAVED': 'تم الحفظ',
      'ACCOUNT_EDIT_ADDRESS': 'تعديل العنوان',
      'ACCOUNT_ADD_ADDRESS': 'إضافة عنوان',
      'ACCOUNT_ADDRESS_FIRST': 'الاسم الأول',
      'ACCOUNT_ADDRESS_LAST': 'اسم العائلة',
      'ACCOUNT_ADDRESS_STREET': 'عنوان الشارع',
      'ACCOUNT_ADDRESS_CITY': 'المدينة',
      'ACCOUNT_ADDRESS_STATE': 'المحافظة / المنطقة',
      'ACCOUNT_ADDRESS_ZIP': 'الرمز البريدي',
      'ACCOUNT_ADDRESS_COUNTRY': 'الدولة',
      'ACCOUNT_ADDRESS_EMPTY': 'لا يوجد عنوان محفوظ. أضف عنواناً لتسريع عملية الشراء.',
      'ACCOUNT_REQUIRED': 'هذا الحقل مطلوب',
      'ACCOUNT_ZIP_INVALID': 'أدخل رمزاً بريدياً صحيحاً',
      'ACCOUNT_SAVE_ADDRESS': 'حفظ العنوان',
      'ACCOUNT_SAVING': 'جارٍ الحفظ...',
      'ACCOUNT_CANCEL': 'إلغاء',
      'DRAWER_NEW_ARRIVALS': 'وصل حديثاً',
      'AUTH_LOGIN_SUB_SHORT': 'ادخل إلى حسابك',
      'AUTH_PANEL_TITLE': 'تسوّق بتجربة فاخرة.',
      'AUTH_PANEL_SUB': 'انضم لآلاف العملاء الذين يستمتعون بمنتجات مختارة بعناية، توصيل سريع، ودفع آمن.',
      'AUTH_PANEL_POINT_SECURE': 'دفع مشفّر وآمن بـ SSL',
      'AUTH_PANEL_POINT_TRACK': 'تتبّع مباشر لطلباتك',
      'AUTH_PANEL_POINT_PAY': 'مدفوعات آمنة بالبطاقة عبر Stripe',
      'NAV_MY_ORDERS': 'طلباتي',
      'NAV_LOGOUT': 'تسجيل خروج',
      'NAV_MENU': 'القائمة',
      'NAV_TOGGLE_MENU': 'فتح أو إغلاق القائمة',
      'NAV_MOBILE_NAV': 'قائمة التنقل على الهاتف',
      'NAV_CLOSE_MENU': 'إغلاق القائمة',
      'BRAND_TAGLINE': 'متجر مميز',
      'ADMIN_DASHBOARD': 'لوحة التحكم',
      'ADMIN_PRODUCTS': 'المنتجات',
      'ADMIN_CATEGORIES': 'التصنيفات',
      'ADMIN_ORDERS': 'الطلبات',
      'ADMIN_ORDERS_DESCRIPTION': 'راجع الطلبات وحدّث حالتها وتابع التجهيز والتوصيل.',
      'ADMIN_FROM_DATE': 'من',
      'ADMIN_TO_DATE': 'إلى',
      'ADMIN_VIEW_ORDER': 'عرض تفاصيل الطلب',
      'ADMIN_CHANGE_STATUS': 'تغيير حالة الطلب',
      'ADMIN_FILTER_STATUS': 'تصفية حسب الحالة',
      'ADMIN_ORDER_DETAILS': 'تفاصيل الطلب',
      'ADMIN_INVOICE': 'فاتورة',
      'ADMIN_PRINT_INVOICE': 'طباعة الفاتورة',
      'ADMIN_CLOSE': 'إغلاق',
      'ADMIN_LOADING_ORDER': 'جار تحميل تفاصيل الطلب…',
      'ADMIN_DISCOUNT': 'الخصم',
      'ADMIN_EMAIL': 'البريد الإلكتروني',
      'ADMIN_PHONE': 'رقم الهاتف',
      'ADMIN_NOT_AVAILABLE': 'غير مسجل في الحساب',
      'ADMIN_ALL_STATUSES': 'كل الحالات',
      'ADMIN_PENDING': 'قيد الانتظار',
      'ADMIN_PAID': 'مدفوع',
      'ADMIN_PAYMENT_FAILED': 'فشل الدفع',
      'ADMIN_SHIPPED': 'تم الشحن',
      'ADMIN_DELIVERED': 'تم التوصيل',
      'ADMIN_SEARCH_ORDERS': 'ابحث بالبريد الإلكتروني للعميل…',
      'ADMIN_ORDERS_COUNT': 'طلبات',
      'ADMIN_DATE': 'التاريخ',
      'ADMIN_PAYMENT': 'الدفع',
      'ADMIN_DELIVERY': 'التوصيل',
      'ADMIN_SHIPPING_ADDRESS': 'عنوان الشحن',
      'ADMIN_SUBTOTAL': 'المجموع الفرعي',
      'ADMIN_SHIPPING': 'الشحن',
      'ADMIN_LOADING_ORDERS': 'جار تحميل الطلبات…',
      'ADMIN_NO_ORDERS_FOUND': 'لا توجد طلبات.',
      'ADMIN_PAGE': 'صفحة',
      'ADMIN_OF': 'من',
      'ADMIN_CUSTOMERS': 'العملاء',
      'ADMIN_COUPONS': 'الكوبونات',
      'ADMIN_LOCATIONS': 'المواقع',
      'ADMIN_LANDING': 'صفحات الهبوط',
      'ADMIN_WEBHOOKS': 'الربط الخارجي',
      'ADMIN_SETTINGS': 'الإعدادات',
      'ADMIN_EMAIL_SETTINGS': 'تصميم البريد',
      'ADMIN_WEBHOOKS_TITLE': 'الربط الخارجي',
      'ADMIN_WEBHOOKS_DESCRIPTION': 'أرسل أحداث الطلبات وبدء النماذج إلى أي خدمة خارجية.',
      'ADMIN_WEBHOOK_ENDPOINT': 'رابط الاستقبال',
      'ADMIN_WEBHOOK_EVENTS': 'الأحداث المشترك بها',
      'ADMIN_WEBHOOK_ORDER_CREATED': 'إنشاء طلب جديد',
      'ADMIN_WEBHOOK_FORM_STARTED': 'بدء تعبئة النموذج',
      'ADMIN_WEBHOOK_ENABLED': 'تفعيل إرسال الأحداث',
      'ADMIN_WEBHOOK_SAVE': 'حفظ الإعدادات',
      'ADMIN_WEBHOOK_SAVING': 'جارٍ الحفظ...',
      'ADMIN_WEBHOOK_SECRET_NOTICE': 'انسخ هذا المفتاح الآن، لن يظهر مرة أخرى.',
      'ADMIN_WEBHOOK_LOGS': 'آخر محاولات الإرسال',
      'ADMIN_WEBHOOK_NO_LOGS': 'لا توجد محاولات إرسال حتى الآن.',
      'ADMIN_WEBHOOK_DELIVERED': 'تم الإرسال',
      'ADMIN_WEBHOOK_FAILED': 'فشل الإرسال',
      'ADMIN_WEBHOOK_ATTEMPT': 'المحاولة',
      'ADMIN_WEBHOOK_VALIDATION': 'أدخل رابطًا صحيحًا واختر حدثًا واحدًا على الأقل.',
      'ADMIN_MANAGE': 'الإدارة',
      'ADMIN_BACK_TO_STORE': 'العودة للمتجر',
      'ADMIN_LOG_OUT': 'تسجيل الخروج',
      'ADMIN_MENU': 'القائمة',
      'ADMIN_LIVE_OVERVIEW': 'نظرة مباشرة على أداء متجرك.',
      'ADMIN_REFRESH': 'تحديث',
      'ADMIN_LOADING_DASHBOARD': 'جار تحميل لوحة التحكم…',
      'ADMIN_DASHBOARD_LOAD_ERROR': 'تعذر تحميل لوحة التحكم. حاول مرة أخرى.',
      'ADMIN_TOTAL_REVENUE': 'إجمالي الإيرادات',
      'ADMIN_REGISTERED': 'مسجل',
      'ADMIN_AVG_ORDER': 'متوسط قيمة الطلب',
      'ADMIN_PRODUCTS_LIVE': 'منتج متاح',
      'ADMIN_SALES_7_DAYS': 'المبيعات — آخر ٧ أيام',
      'ADMIN_THIS_WEEK': 'هذا الأسبوع',
      'ADMIN_THIS_MONTH': 'هذا الشهر',
      'ADMIN_RECENT_ORDERS': 'أحدث الطلبات',
      'ADMIN_VIEW_ALL': 'عرض الكل',
      'ADMIN_BEST_SELLERS': 'الأكثر مبيعاً',
      'ADMIN_LOW_STOCK': 'مخزون منخفض',
      'ADMIN_PRODUCTS_LINK': 'المنتجات',
      'ADMIN_NO_ORDERS': 'لا توجد طلبات بعد.',
      'ADMIN_NO_SALES': 'لا توجد بيانات مبيعات بعد.',
      'ADMIN_STOCK_HINT': '٥ أو أقل متبقية',
      'ADMIN_WELL_STOCKED': 'كل المنتجات متوفرة بمخزون جيد.',
      'ADMIN_LOCATIONS_TITLE': 'المواقع',
      'ADMIN_LOCATIONS_DESCRIPTION': 'إدارة المحافظات والمدن المخزنة في قاعدة البيانات. لا حاجة لتحرير JSON.',
      'ADMIN_GOVERNORATES': 'المحافظات',
      'ADMIN_ADD_GOVERNORATE': 'إضافة محافظة',
      'ADMIN_ADD_GOVERNORATE_DESC': 'أضف الاسم بالإنجليزية، الاسم بالعربية، وكود ثابت.',
      'ADMIN_CODE': 'الكود',
      'ADMIN_ENGLISH_NAME': 'الاسم بالإنجليزية',
      'ADMIN_ARABIC_NAME': 'الاسم بالعربية',
      'ADMIN_ADD_GOVERNORATE_BTN': 'إضافة محافظة',
      'ADMIN_LOADING_LOCATIONS': 'جارٍ تحميل المواقع...',
      'ADMIN_DIRECTORY': 'الدليل',
      'ADMIN_GOVERNORATES_AND_CITIES': 'المحافظات والمدن',
      'ADMIN_DELETE_GOVERNORATE': 'حذف المحافظة',
      'ADMIN_CITIES': 'المدن',
      'ADMIN_AVAILABLE_IN_CHECKOUT': 'متاحة في الشحن',
      'ADMIN_ADD_CITY': 'إضافة مدينة',
      'ADMIN_NO_GOVERNORATES': 'لا توجد محافظات بعد',
      'ADMIN_NO_GOVERNORATES_DESC': 'أضف المحافظة الأولى أعلاه لبدء بناء الدليل.',
      'ADMIN_LANDING_PAGES_TITLE': 'صفحات الهبوط',
      'ADMIN_LANDING_PAGES_DESCRIPTION': 'أنشئ إعلانات صفحة واحدة احترافية لمنتجاتك وشارك الرابط في أي مكان.',
      'ADMIN_NEW_LANDING_PAGE': '+ صفحة هبوط جديدة',
      'ADMIN_LOADING_LANDING_PAGES': 'جارٍ تحميل صفحات الهبوط...',
      'ADMIN_NO_LANDING_PAGES': 'لا توجد صفحات هبوط بعد',
      'ADMIN_NO_LANDING_PAGES_DESC': 'أنشئ صفحة هبوط للمنتج الأولى وانشرها برابط قابل للمشاركة.',
      'ADMIN_CREATE_LANDING_PAGE': 'أنشئ واحدة الآن',
      'ADMIN_TITLE': 'العنوان',
      'ADMIN_LINK': 'الرابط',
      'ADMIN_SECTIONS': 'الأقسام',
      'ADMIN_VIEWS': 'المشاهدات',
      'ADMIN_UPDATED': 'آخر تحديث',
      'ADMIN_SLUG': 'الرابط المختصر',
      'ADMIN_PUBLISHED': 'منشور',
      'ADMIN_DRAFT': 'مسودة',
      'ADMIN_LAST_UPDATED': 'آخر تحديث',
      'ADMIN_VIEW_PAGE': 'عرض الصفحة',
      'ADMIN_EDIT_PAGE': 'تعديل الصفحة',
      'ADMIN_EDIT_LANDING_PAGE': 'تعديل صفحة الهبوط',
      'ADMIN_LANDING_PAGE_INTRO': 'أنشئ الأقسام، اربط المنتج، ثم انشر وشارك الرابط.',
      'ADMIN_SAVING': 'جارٍ الحفظ...',
      'ADMIN_SAVE_LANDING_PAGE': 'حفظ صفحة الهبوط',
      'ADMIN_LOADING': 'جارٍ التحميل...',
      'ADMIN_LANDING_PAGE_FORM_INTRO': 'أعطِ الصفحة اسمًا، اختر المنتج الذي تبيعه، ثم أضف الأقسام التي تحتاجها فقط.',
      'ADMIN_PAGE_TITLE': 'عنوان الصفحة',
      'ADMIN_PAGE_TITLE_PLACEHOLDER': 'مثال: عرض إطلاق زجاجة Eco',
      'ADMIN_SHARE_LINK_NAME': 'اسم الرابط للمشاركة',
      'ADMIN_SLUG_PLACEHOLDER': 'eco-bottle-offer',
      'ADMIN_PRODUCT_TO_SELL': 'المنتج للبيع',
      'ADMIN_OPTIONAL': 'اختياري',
      'ADMIN_NONE': '— لا شيء —',
      'ADMIN_PUBLISH_NOW': 'انشر الآن',
      'ADMIN_PUBLIC_LINK': 'رابطك العام',
      'ADMIN_PAGE_SECTIONS': 'أقسام الصفحة',
      'ADMIN_ADD_BLOCKS_IN_ORDER': 'أضف الكتل بالترتيب الذي يجب أن تظهر به في الصفحة.',
      'ADMIN_CHOOSE_BLOCK': 'اختر كتلة...',
      'ADMIN_ADD': '+ إضافة',
      'ADMIN_NO_SECTIONS_YET': 'لا توجد أقسام بعد',
      'ADMIN_START_WITH_HERO': 'ابدأ بقسم Hero، ثم أضف الميزات والمراجعات والأسئلة الشائعة ونموذج الطلب.',
      'ADMIN_SECTION_LABEL_PLACEHOLDER': 'تسمية القسم (تظهر فوق المحتوى)',
      'ADMIN_MOVE_UP': 'تحريك للأعلى',
      'ADMIN_MOVE_DOWN': 'تحريك للأسفل',
      'ADMIN_HIDE': 'إخفاء',
      'ADMIN_SHOW': 'إظهار',
      'ADMIN_REMOVE': 'إزالة',
      'ADMIN_IMAGE_URL': 'رابط الصورة',
      'ADMIN_IMAGE_URL_PLACEHOLDER': 'https://… أو Images/Products/photo.jpg',
      'ADMIN_HEADLINE': 'العنوان الرئيسي',
      'ADMIN_BODY_TEXT': 'نص المحتوى',
      'ADMIN_BUTTON_TEXT': 'نص الزر',
      'ADMIN_BUTTON_LINK': 'رابط الزر',
      'ADMIN_BUTTON_LINK_PLACEHOLDER': 'مثال: #order',
      'ADMIN_ADD_ITEM': '+ إضافة عنصر',
      'ADMIN_ICON': 'أيقونة',
      'ADMIN_RATING': 'التقييم',
      'ADMIN_REVIEW': 'المراجعة',
      'ADMIN_QUESTION': 'السؤال',
      'ADMIN_ANSWER': 'الإجابة',
      'ADMIN_CUSTOMERS_TITLE': 'العملاء',
      'ADMIN_CUSTOMERS_DESCRIPTION': 'جميع المسجلين في المتجر، طلباتهم وصلاحيات الإدارة.',
      'ADMIN_SEARCH_CUSTOMERS_PLACEHOLDER': 'ابحث بالاسم أو البريد الإلكتروني...',
      'ADMIN_CUSTOMER_FILTER': 'تصفية حسب الصلاحية',
      'ADMIN_CUSTOMER_FILTER_ALL': 'كل العملاء',
      'ADMIN_CUSTOMER_FILTER_CUSTOMERS': 'العملاء فقط',
      'ADMIN_CUSTOMER_FILTER_ADMINS': 'المسؤولون فقط',
      'ADMIN_CUSTOMERS_COUNT': 'عملاء',
      'ADMIN_TOTAL_SPENT': 'إجمالي الإنفاق',
      'ADMIN_VIEW': 'عرض',
      'ADMIN_ROLES': 'الأدوار',
      'ADMIN_CUSTOMER_ROLE': 'عميل',
      'ADMIN_ADMIN_ROLE': 'مسؤول',
      'ADMIN_REMOVE_ADMIN': 'إزالة المسؤول',
      'ADMIN_MAKE_ADMIN': 'تعيين مسؤول',
      'ADMIN_NO_CUSTOMERS_FOUND': 'لا توجد عملاء.',
      'ADMIN_LOADING_CUSTOMER': 'جار تحميل العميل...',
      'ADMIN_SPENT': 'تم الإنفاق',
      'ADMIN_CUSTOMER_NO_ORDERS': 'هذا العميل ليس لديه طلبات بعد.',
      'ADMIN_COUPONS_TITLE': 'الكوبونات',
      'ADMIN_COUPONS_DESCRIPTION': 'أنشئ كوبونات الخصم التي يمكن للعملاء تطبيقها في السلة.',
      'ADMIN_NEW_COUPON': '+ كوبون جديد',
      'ADMIN_EDIT_COUPON': 'تعديل الكوبون',
      'ADMIN_COUPON_CODE': 'الرمز',
      'ADMIN_COUPON_TYPE': 'النوع',
      'ADMIN_COUPON_PERCENTAGE': 'نسبة مئوية (%)',
      'ADMIN_COUPON_FIXED_AMOUNT': 'مبلغ ثابت ($)',
      'ADMIN_COUPON_VALUE': 'القيمة',
      'ADMIN_COUPON_EXPIRY_DATE': 'تاريخ الانتهاء',
      'ADMIN_COUPON_MAX_USES': 'الحد الأقصى للاستخدام',
      'ADMIN_COUPON_ACTIVE': 'نشط',
      'ADMIN_SAVE_COUPON': 'حفظ الكوبون',
      'ADMIN_ALL_COUPONS': 'جميع الكوبونات',
      'ADMIN_USAGE': 'الاستخدام',
      'ADMIN_EXPIRY': 'الانتهاء',
      'ADMIN_COUPON_INACTIVE': 'غير نشط',
      'ADMIN_COUPON_EXPIRED': 'منتهي الصلاحية',
      'ADMIN_NO_COUPONS_YET': 'لا توجد كوبونات بعد. أنشئ أول كوبون لك!',
      'ADMIN_EDIT_CATEGORY': 'تعديل التصنيف',
      'ADMIN_CATEGORY_NAME_PLACEHOLDER': 'مثال: المنزل والحياة',
      'ADMIN_CATEGORY_DESCRIPTION_PLACEHOLDER': 'أضف وصفًا قصيرًا لهذا التصنيف',
      'ADMIN_SAVE_CHANGES': 'حفظ التغييرات',
      'ADMIN_ADD_CATEGORY': 'إضافة تصنيف',
      'ADMIN_SEARCH_CATEGORIES': 'البحث في التصنيفات',
      'ADMIN_SEARCH_CATEGORIES_PLACEHOLDER': 'ابحث في التصنيفات...',
      'ADMIN_NO_PAID_ORDERS_7_DAYS': 'لا توجد طلبات مدفوعة في آخر 7 أيام — ستظهر الإيرادات هنا عند وصول الطلبات.',
      'ADMIN_SOLD': 'تم البيع',
      'ADMIN_LEFT': 'متبقي',
      'ADMIN_DASH': '—',
      'ADMIN_COUPON': 'كوبون',
      'ADMIN_NAME': 'الاسم',
      'ADMIN_DESCRIPTION': 'الوصف',
      'ADMIN_NEW_CATEGORY': 'تصنيف جديد',
      'ADMIN_NAME_REQUIRED': 'الاسم مطلوب.',
      'ADMIN_DESCRIPTION_REQUIRED': 'الوصف مطلوب.',
      'ADMIN_LOADING_CATEGORIES': 'جار تحميل التصنيفات…',
      'ADMIN_NO_CATEGORIES': 'لا توجد تصنيفات.',
      'ADMIN_ORDER': 'الطلب',
      'ADMIN_CUSTOMER': 'العميل',
      'ADMIN_ITEMS': 'العناصر',
      'ADMIN_STATUS': 'الحالة',
      'ADMIN_TOTAL': 'الإجمالي',

      // About
      'ABOUT_EYEBROW': 'عن Eco',
      'ABOUT_TITLE': 'منتجات مختارة بعناية لحياتك اليومية.',
      'ABOUT_INTRO': 'Eco متجر مميز يعتمد على منتجات مختارة بعناية وتجربة تسوق بسيطة وممتعة. نؤمن أن التصميم الجيد والجودة يجب أن يكونا متاحين للجميع.',
      'ABOUT_SHOP_CTA': 'استكشف المتجر',
      'ABOUT_VALUES_EYEBROW': 'ما نؤمن به',
      'ABOUT_VALUES_TITLE': 'قيمنا',
      'ABOUT_VALUE_QUALITY_TITLE': 'الجودة أولاً',
      'ABOUT_VALUE_QUALITY_DESC': 'نختار كل منتج بعناية ونتأكد من جودته وتصميمه وقيمته العملية.',
      'ABOUT_VALUE_SUSTAINABILITY_TITLE': 'الاستدامة',
      'ABOUT_VALUE_SUSTAINABILITY_DESC': 'نتعاون مع علامات تجارية تهتم بالمصادر المسؤولة والتغليف الأفضل.',
      'ABOUT_VALUE_CUSTOMER_TITLE': 'نهتم بالعميل',
      'ABOUT_VALUE_CUSTOMER_DESC': 'رضاك أولويتنا، مع تجربة إرجاع سهلة ودعم مستمر عند الحاجة.',
      'ABOUT_VALUE_PRICING_TITLE': 'أسعار عادلة',
      'ABOUT_VALUE_PRICING_DESC': 'الجودة المميزة لا تعني أسعاراً مبالغاً فيها، ونعمل دائماً على إبقاء الأسعار مناسبة.',

      // Shop & Items
      'SHOP_ADD_TO_CART': 'أضف للسلة',
      'SHOP_VIEW_DETAILS': 'عرض التفاصيل',
      'SHOP_PREMIUM_PICKS': 'مختارات مميزة',
      'SHOP_ALL_PRODUCTS': 'كل المنتجات',
      'SHOP_FEATURED': 'منتجات مختارة',
      'SHOP_NO_PRODUCTS': 'لم يتم العثور على منتجات',
      'SHOP_NO_PRODUCTS_DESC': 'لا توجد منتجات متاحة للعرض حالياً.',
      'SHOP_REFRESH': 'تحديث المنتجات',
      'SHOP_EYEBROW': 'منتجات مختارة للحياة اليومية',
      'SHOP_TITLE': 'اعثر على منتجك المفضل التالي',
      'SHOP_INTRO': 'اكتشف منتجات عالية الجودة مختارة بعناية من أجلك.',
      'SHOP_PRODUCTS_AVAILABLE': 'منتج متاح',
      'BS_EYEBROW': 'تشكيلة فاخرة مختارة بعناية',
      'BS_TITLE': 'الأكثر طلباً',
      'BS_INTRO': 'اكتشف تشكيلة من أرفع المنتجات في متجر Eco، مختارة بعناية لأعلى معايير الجودة والحرفية.',
      'BS_FEATURED_COUNT': 'منتج مختار',
      'BS_UPDATING': 'جاري تحديث المنتجات...',
      'BS_NO_PRODUCTS': 'لم يتم العثور على منتجات',
      'BS_NO_PRODUCTS_DESC': 'لا توجد منتجات متاحة للعرض حالياً.',

      // Checkout payment methods
      'CHECKOUT_PAYMENT_METHOD': 'طريقة الدفع',
      'CHECKOUT_PAY_STRIPE': 'بطاقة بنكية (Visa)',
      'CHECKOUT_PAY_STRIPE_DESC': 'دفع آمن بالبطاقة الائتمانية',
      'CHECKOUT_PAY_INSTAPAY': 'انستاباي',
      'CHECKOUT_PAY_INSTAPAY_DESC': 'تحويل فوري من البنك أو المحفظة',
      'CHECKOUT_PAY_VODAFONE': 'فودافون كاش',
      'CHECKOUT_PAY_VODAFONE_DESC': 'ادفع من محفظة فودافون كاش',
      'CHECKOUT_PAY_COD': 'الدفع عند التسليم',
      'CHECKOUT_PAY_COD_DESC': 'ادفع كاش للمندوب عند الاستلام',
      'CHECKOUT_PAY_UNAVAILABLE': 'غير متاح حالياً',
      'CHECKOUT_WALLET_INSTRUCTIONS': 'حوّل إجمالي الطلب على الرقم 0100 990 1702، وبعتنا صورة التحويل واتساب لتأكيد طلبك.',
      'CHECKOUT_WALLET_INSTRUCTIONS_PREFIX': 'حوّل إجمالي الطلب على الرقم',
      'CHECKOUT_WALLET_INSTRUCTIONS_SUFFIX': '، وبعتنا صورة التحويل واتساب لتأكيد طلبك.',
      'CHECKOUT_COD_INSTRUCTIONS': 'ادفع كاش للمندوب لما يوصلك الطلب.',

      // Auth social + shipping
      'AUTH_GOOGLE': 'الدخول بواسطة جوجل',
      'AUTH_OR': 'أو',
      'BASKET_SHIPPING_FROM': 'يبدأ من',

      // Wishlist
      'WISHLIST_EYEBROW': 'محفوظة لوقت لاحق',
      'WISHLIST_TITLE': 'قائمة المفضلة',
      'WISHLIST_INTRO': 'كل المنتجات اللي عجبتك، محفوظة في مكان واحد وجاهزة في أي وقت.',
      'WISHLIST_COUNT': 'منتج محفوظ',
      'WISHLIST_SIGNIN_TITLE': 'سجّل الدخول لمشاهدة المفضلة',
      'WISHLIST_SIGNIN_DESC': 'قائمة المفضلة مرتبطة بحسابك، فمنتجاتك المحفوظة بتتبعك على كل أجهزتك.',
      'WISHLIST_SIGNIN_CTA': 'تسجيل الدخول',
      'WISHLIST_EMPTY_TITLE': 'قائمة المفضلة فاضية',
      'WISHLIST_EMPTY_DESC': 'اضغط على القلب في أي منتج لتحفظه هنا لوقت لاحق.',
      'WISHLIST_EMPTY_CTA': 'تسوّق الآن',
      'BS_REFRESH': 'تحديث المنتجات',
      'SHOP_TOGGLE_FILTERS': 'فتح أو إغلاق الفلاتر',
      'SHOP_FILTERS_SORTING': 'الفلاتر والترتيب',
      'SHOP_OPEN': 'فتح',
      'SHOP_CLOSE': 'إغلاق',
      'SHOP_BROWSE': 'تصفح',
      'SHOP_SORTING': 'الترتيب',
      'SHOP_SORT_PRODUCTS': 'ترتيب المنتجات',
      'SHOP_SORT_NAME': 'الاسم',
      'SHOP_SORT_PRICE_ASC': 'السعر: من الأقل إلى الأعلى',
      'SHOP_SORT_PRICE_DESC': 'السعر: من الأعلى إلى الأقل',
      'SHOP_ALL': 'الكل',
      'SHOP_SEARCH': 'بحث',
      'SHOP_SEARCH_PLACEHOLDER': 'ابحث عن المنتجات...',
      'SHOP_RESET_FILTERS': 'إعادة تعيين الفلاتر',
      'SHOP_OF': 'من',
      'SHOP_PRODUCTS': 'منتج',
      'SHOP_UPDATING': 'جارٍ تحديث المنتجات...',
      'SHOP_PAGINATION': 'صفحات المنتجات',
      'SHOP_PRODUCT_RATING': 'تقييم المنتج',
      'SHOP_NO_REVIEWS': '0.0 (0)',
      'PRODUCT_IN_STOCK': 'متوفر',
      'PRODUCT_REVIEWS': 'تقييمات العملاء',
      'PRODUCT_SAVE': 'وفر',
      'PRODUCT_DISCOUNT': 'خصم',
      'PRODUCT_ADD_TO_BASKET': 'أضف للسلة',
      'PRODUCT_ADDED_TO_BASKET': 'تمت الإضافة للسلة',
      'PRODUCT_DESCRIPTION': 'الوصف',
      'PRODUCT_REVIEWS_TAB': 'التقييمات',
      'PRODUCT_OVERVIEW': 'نظرة عامة على المنتج',
      'PRODUCT_SPECIFICATIONS': 'مواصفات المنتج',
      'PRODUCT_PERK_1': 'صناعة عالية الجودة مصممة للاستخدام اليومي طويل الأمد.',
      'PRODUCT_PERK_2': 'تم اختباره بعناية لتحقيق أفضل كفاءة في الأداء والطاقة.',
      'PRODUCT_PERK_3': 'يشمل جميع الملحقات والوثائق الأساسية داخل العبوة.',
      'PRODUCT_BASED_ON_REVIEWS': 'بناءً على تقييم',
      'PRODUCT_NO_REVIEWS_YET': 'لا توجد تقييمات بعد — كن أول من يكتب تقييماً!',
      'PRODUCT_WRITE_REVIEW': 'اكتب تقييماً',
      'PRODUCT_CANCEL_REVIEW': 'إلغاء التقييم',
      'PRODUCT_LEAVE_REVIEW': 'أضف تقييمك',
      'PRODUCT_OVERALL_RATING': 'تقييمك العام:',
      'PRODUCT_OUT_OF_STARS': 'من 5 نجوم',
      'PRODUCT_REVIEWING_AS': 'التقييم باسم',
      'PRODUCT_REVIEW_HEADLINE': 'عنوان التقييم',
      'PRODUCT_REVIEW_TITLE_PLACEHOLDER': 'مثال: جودة ممتازة وسهل الاستخدام!',
      'PRODUCT_REVIEW_EXPERIENCE': 'تقييمك وتجربتك *',
      'PRODUCT_REVIEW_PLACEHOLDER': 'شارك رأيك عن جودة المنتج ومميزاته وتجربتك معه...',
      'PRODUCT_SUBMITTING_REVIEW': 'جارٍ الإرسال…',
      'PRODUCT_SUBMIT_REVIEW': 'إرسال التقييم',
      'PRODUCT_CUSTOMER_FEEDBACK': 'آراء العملاء',
      'PRODUCT_LOADING_REVIEWS': 'جارٍ تحميل التقييمات…',
      'PRODUCT_NO_REVIEWS': 'لا توجد تقييمات بعد',
      'PRODUCT_FIRST_REVIEW': 'كن أول من يشارك تجربته مع هذا المنتج.',
      'PRODUCT_LOAD_ERROR': 'تعذر تحميل المنتج',
      'PRODUCT_NOT_FOUND': 'المنتج غير موجود',
      'PRODUCT_NOT_FOUND_DESC': 'المنتج الذي تبحث عنه غير موجود أو غير متاح حالياً.',
      'PRODUCT_BROWSE_ALL': 'تصفح كل المنتجات',
      'ADMIN_PRODUCT_NEW': 'منتج جديد',
      'ADMIN_PRODUCT_EDIT': 'تعديل المنتج',
      'ADMIN_PRODUCT_NAME': 'الاسم',
      'ADMIN_PRODUCT_CATEGORY': 'التصنيف',
      'ADMIN_PRODUCT_SELECT_CATEGORY': 'اختر التصنيف',
      'ADMIN_PRODUCT_CURRENT_PRICE': 'السعر الحالي',
      'ADMIN_PRODUCT_ORIGINAL_PRICE': 'السعر الأصلي',
      'ADMIN_PRODUCT_DESCRIPTION': 'الوصف',
      'ADMIN_PRODUCT_IMAGES': 'الصور',
      'ADMIN_PRODUCT_CREATE': 'إضافة المنتج',
      'ADMIN_PRODUCT_TRACK_STOCK': 'تتبع المخزون',
      'ADMIN_PRODUCT_QUANTITY': 'الكمية المتاحة',
      'ADMIN_PRODUCT_PACKAGE_DETAILS': 'بيانات الشحن',
      'ADMIN_PRODUCT_OPTIONAL': 'اختياري',
      'ADMIN_PRODUCT_LENGTH': 'الطول',
      'ADMIN_PRODUCT_WIDTH': 'العرض',
      'ADMIN_PRODUCT_HEIGHT': 'الارتفاع',
      'ADMIN_PRODUCT_WEIGHT': 'الوزن',
      'ADMIN_PRODUCT_MORE_SPECS': 'مواصفات إضافية',
      'ADMIN_PRODUCT_CHOOSE_IMAGES': 'اختيار الصور',
      'ADMIN_PRODUCT_IMAGE_TYPES': 'PNG أو JPG أو WEBP',
      'ADMIN_PRODUCT_DROP_IMAGES': 'أو اسحب الصور إلى هنا',
      'ADMIN_PRODUCT_PREVIEW_COUNT': 'معاينة',
      'ADMIN_PRODUCTS_DESCRIPTION': 'أنشئ منتجات الكتالوج وعدّلها واحذفها.',
      'ADMIN_CLOSE_FORM': 'إغلاق النموذج',
      'ADMIN_PRODUCT_NEW_ACTION': '+ منتج جديد',
      'ADMIN_ALL_PRODUCTS': 'كل المنتجات',
      'ADMIN_SEARCH_PRODUCTS': 'ابحث باسم المنتج…',
      'ADMIN_ALL_CATEGORIES': 'كل التصنيفات',
      'ADMIN_PRODUCT': 'المنتج',
      'ADMIN_CATEGORY': 'التصنيف',
      'ADMIN_PRICE': 'السعر',
      'ADMIN_STOCK': 'المخزون',
      'ADMIN_ACTIONS': 'الإجراءات',
      'ADMIN_LOADING_PRODUCTS': 'جارٍ تحميل المنتجات…',
      'ADMIN_NO_PRODUCTS': 'لا توجد منتجات.',
      'ADMIN_NOT_TRACKED': 'غير متتبع',
      'ADMIN_DELETE': 'حذف',
      'ADMIN_CANCEL': 'إلغاء',
      'ADMIN_PRODUCT_NAME_REQUIRED': 'الاسم مطلوب.',
      'ADMIN_PRODUCT_NAME_PLACEHOLDER': 'مثال: ماكينة قهوة سيراميك',
      'ADMIN_PRODUCT_CATEGORY_REQUIRED': 'اختر تصنيفاً.',
      'ADMIN_PRODUCT_PRICE_REQUIRED': 'السعر الحالي مطلوب.',
      'ADMIN_PRODUCT_DESCRIPTION_REQUIRED': 'الوصف مطلوب.',
      'ADMIN_PRODUCT_DESCRIPTION_PLACEHOLDER': 'اكتب وصفاً مختصراً للمنتج…',
      'ADMIN_PRODUCT_SPECIFICATIONS_JSON': 'المواصفات (JSON)',
      'ADMIN_PRODUCT_SPECS_HINT': 'تفاصيل تقنية اختيارية لصفحة المنتج.',
      'ADMIN_PRODUCT_SPECS_PLACEHOLDER': '[{"label":"السعة","value":"1.5 لتر"}]',
      'ADMIN_PRODUCT_SPECS_FORMAT': 'أضف كل مواصفة في شكل اسم وقيمة.',
      'ADMIN_PRODUCT_REPLACE_IMAGES': '(اختياري؛ يستبدل الصور الحالية)',
      'ADMIN_PRODUCT_IMAGE_REQUIRED': 'يجب اختيار صورة واحدة على الأقل للمنتج الجديد.',
      'ADMIN_PRODUCT_SAVING': 'جارٍ الحفظ…',
      'ADMIN_PRODUCT_SAVE_CHANGES': 'حفظ التغييرات',
      'ADMIN_PRODUCTS_LOAD_ERROR': 'تعذر تحميل المنتجات.',
      'ADMIN_PRODUCT_FORM_ERROR': 'يرجى ملء الحقول المحددة.',
      'ADMIN_PRODUCT_STOCK_REQUIRED': 'أدخل الكمية المتاحة أو أوقف تتبع المخزون.',
      'ADMIN_PRODUCT_SPECS_ERROR': 'يجب أن تكون المواصفات مصفوفة JSON صحيحة تحتوي على label وvalue.',
      'ADMIN_PRODUCT_CREATED': 'تم إنشاء المنتج.',
      'ADMIN_PRODUCT_UPDATED': 'تم تحديث المنتج.',
      'ADMIN_PRODUCT_SAVE_ERROR': 'تعذر حفظ المنتج.',
      'ADMIN_PRODUCT_DELETE_CONFIRM': 'هل تريد حذف هذا المنتج؟ لا يمكن التراجع عن ذلك.',
      'ADMIN_PRODUCT_DELETED': 'تم حذف المنتج.',
      'ADMIN_PRODUCT_DELETE_ERROR': 'تعذر حذف المنتج.',
      'WISHLIST_ADD': 'أضف إلى المفضلة',
      'WISHLIST_REMOVE': 'إزالة من المفضلة',

      // Home
      'HOME_WELCOME': 'مرحباً بك',
      'HOME_HERO_TITLE': 'منتجات أفضل لحياة يومية أسهل.',
      'HOME_HERO_SUBTITLE': 'اكتشف أساسيات مختارة بعناية مع تجربة تسوق مميزة صُممت من أجلك.',
      'HOME_SHOP_NOW': 'تسوق الآن',
      'HOME_BRANDS': 'علامة تجارية',
      'HOME_RATING': 'التقييم',
      'HOME_SHOP_BY_NEED': 'تسوق حسب احتياجك',
      'HOME_FEATURED_CATEGORIES': 'أقسام مميزة',
      'HOME_VIEW_ALL': 'عرض الكل',
      'HOME_CAREFULLY_SELECTED': 'مختارة بعناية',
      'HOME_SHOP_ALL': 'تسوق الكل',
      'HOME_ECO_COLLECTION': 'مجموعة Eco',
      'HOME_FREE_SHIPPING': 'شحن مجاني',
      'HOME_FREE_SHIPPING_DESC': 'للطلبات التي تزيد عن 50$. توصيل سريع وموثوق إلى بابك.',
      'HOME_EASY_RETURNS': 'استرجاع سهل',
      'HOME_EASY_RETURNS_DESC': 'سياسة استرجاع سهلة لمدة 30 يوماً، دون أسئلة.',
      'HOME_SECURE_PAYMENT': 'دفع آمن',
      'HOME_SECURE_PAYMENT_DESC': 'بيانات الدفع الخاصة بك مشفرة ومحمية دائماً.',
      'HOME_SUPPORT': 'دعم على مدار الساعة',
      'HOME_SUPPORT_DESC': 'فريقنا موجود لمساعدتك في أي وقت وكل أيام الأسبوع.',
      'HOME_READY': 'هل أنت جاهز للتسوق؟',
      'HOME_CTA_TITLE': 'اعثر على منتجك المفضل التالي اليوم.',
      'HOME_CTA_DESC': 'تصفح مئات المنتجات المميزة المختارة بعناية بأسعار رائعة.',

      // Account
      'ACCOUNT_LOADING': 'جارٍ تحميل بيانات حسابك...',
      'ACCOUNT_MEMBER': 'عضو Eco',
      'ACCOUNT_VALUED_CUSTOMER': 'عميلنا العزيز',
      'ACCOUNT_SHOP_MORE': 'تسوق المزيد',
      'ACCOUNT_PROFILE': 'بيانات الملف الشخصي',
      'ACCOUNT_ORDER_HISTORY': 'سجل الطلبات',
      'ACCOUNT_DETAILS': 'تفاصيل الحساب',
      'ACCOUNT_DISPLAY_NAME': 'الاسم الظاهر',
      'ACCOUNT_NOT_SPECIFIED': 'غير محدد',
      'ACCOUNT_STATUS': 'حالة الحساب',
      'ACCOUNT_ACTIVE_VERIFIED': 'نشط وموثّق',
      'ACCOUNT_MEMBERSHIP': 'عضوية Eco',
      'ACCOUNT_STANDARD_MEMBER': 'عضو أساسي',
      'ACCOUNT_PROTECTED': 'حسابك محمي',
      'ACCOUNT_PROTECTED_DESC': 'جلستك مشفرة ومؤمنة ببيانات اعتماد آمنة.',
      'ACCOUNT_YOUR_ORDERS': 'طلباتك',
      'ACCOUNT_REFRESH': 'تحديث',
      'ACCOUNT_LOADING_ORDERS': 'جارٍ تحميل سجل طلباتك...',
      'ACCOUNT_NO_ORDERS': 'لا توجد طلبات حتى الآن',
      'ACCOUNT_NO_ORDERS_DESC': 'عند إتمام عملية شراء، سيظهر سجل طلباتك وتفاصيل التتبع هنا.',
      'ACCOUNT_ORDER': 'الطلب',
      'ACCOUNT_TOTAL_AMOUNT': 'المبلغ الإجمالي',
      'ACCOUNT_ITEMS_COUNT': 'عدد المنتجات',
      'ACCOUNT_NEED_TRACKING': 'هل تحتاج إلى تفاصيل التتبع؟',
      'ACCOUNT_TRACK_ORDER': 'تتبع الطلب',
      'ACCOUNT_WELCOME': 'مرحباً بك في حسابك',
      'ACCOUNT_WELCOME_DESC': 'سجل الدخول لعرض طلباتك وإدارة إعدادات الحساب والاستمتاع بتجربة شراء سلسة.',

      // Basket
      'BASKET_TITLE': 'سلة المشتريات',
      'BASKET_EYEBROW': 'سلتك',
      'BASKET_ITEM': 'منتج في سلتك',
      'BASKET_ITEMS': 'منتجات في سلتك',
      'BASKET_CLEAR': 'تفريغ السلة',
      'BASKET_ITEMS_LABEL': 'منتجات السلة',
      'BASKET_QUANTITY_FOR': 'الكمية للمنتج',
      'BASKET_DECREASE': 'تقليل الكمية',
      'BASKET_INCREASE': 'زيادة الكمية',
      'BASKET_REMOVE': 'إزالة',
      'BASKET_EACH': 'للقطعة',
      'BASKET_CONTINUE': 'متابعة التسوق',
      'BASKET_SUMMARY': 'ملخص الطلب',
      'BASKET_SUBTOTAL': 'المجموع الفرعي',
      'BASKET_SHIPPING': 'الشحن',
      'BASKET_FREE': 'مجاناً',
      'BASKET_FREE_SHIPPING_MSG': 'أضف بقيمة {amount} إضافية للحصول على شحن مجاني!',
      'BASKET_TOTAL': 'الإجمالي',
      'BASKET_CHECKOUT': 'إتمام عملية الشراء',
      'BASKET_EMPTY_TITLE': 'سلتك فارغة',
      'BASKET_EMPTY_SUB': 'يبدو أنك لم تضف أي منتج إلى سلتك بعد. تصفح مجموعتنا المميزة من المنتجات المختارة.',
      'BASKET_EXPLORE': 'تصفح المتجر',
      'BASKET_TRUST_SSL': 'دفع آمن ومشفر بنسبة 100%',
      'BASKET_TRUST_FAST': 'توصيل سريع وموثوق',
      'BASKET_TRUST_PAY': 'خيارات دفع متعددة ومريحة',

      // Checkout
      'CHECKOUT_EYEBROW': 'الدفع الآمن',
      'CHECKOUT_TITLE': 'إتمام طلبك',
      'CHECKOUT_ORDER_PREVIEW_EYEBROW': 'اختياراتك',
      'CHECKOUT_ORDER_PREVIEW': 'المنتجات في طلبك',
      'CHECKOUT_ITEMS': 'منتجات',
      'CHECKOUT_QUANTITY': 'الكمية',
      'CHECKOUT_EMPTY_ORDER': 'سلتك فارغة.',
      'CHECKOUT_BACK': 'العودة للسلة',
      'CHECKOUT_STEP_SHIPPING': 'عنوان التوصيل',
      'CHECKOUT_STEP_SHIPPING_SUB': 'أين ترغب في استلام طلبك؟',
      'CHECKOUT_FIRST_NAME': 'الاسم الأول',
      'CHECKOUT_LAST_NAME': 'اسم العائلة',
      'CHECKOUT_STREET': 'عنوان الشارع والمنزل',
      'CHECKOUT_CITY': 'المدينة',
      'CHECKOUT_STATE': 'المحافظة / المنطقة',
      'CHECKOUT_SELECT_CITY': 'اختر المدينة',
      'CHECKOUT_SELECT_STATE': 'اختر المحافظة',
      'CHECKOUT_SELECT_STATE_FIRST': 'اختر المحافظة أولاً',
      'CHECKOUT_ZIP': 'الرمز البريدي',
      'CHECKOUT_STEP_DELIVERY': 'طريقة التوصيل',
      'CHECKOUT_STEP_DELIVERY_SUB': 'اختر سرعة التوصيل المناسبة لك',
      'CHECKOUT_CITY_DELIVERY': 'التوصيل إلى مدينتك',
      'CHECKOUT_BUSINESS_DAY': 'يوم عمل',
      'CHECKOUT_BUSINESS_DAYS': 'أيام عمل',
      'CHECKOUT_SAVING_ADDRESS': 'جاري حفظ العنوان...',
      'CHECKOUT_UNAVAILABLE': 'الشحن غير متاح لهذه المدينة',
      'CHECKOUT_PLACE_ORDER': 'تأكيد الطلب بأمان',
      'CHECKOUT_PLACING': 'جاري تأكيد الطلب...',
      'CHECKOUT_FIRST_NAME_ERROR': 'الاسم الأول مطلوب (حروف فقط، حرفان على الأقل).',
      'CHECKOUT_LAST_NAME_ERROR': 'اسم العائلة مطلوب (حروف فقط، حرفان على الأقل).',
      'CHECKOUT_STREET_ERROR': 'عنوان الشارع مطلوب (5 أحرف على الأقل).',
      'CHECKOUT_CITY_ERROR': 'المدينة مطلوبة.',
      'CHECKOUT_STATE_ERROR': 'المحافظة أو المنطقة مطلوبة.',
      'CHECKOUT_ZIP_ERROR': 'يرجى إدخال رمز بريدي صحيح (4-10 أرقام).',
      'CHECKOUT_SAVED_ADDRESS_INVALID': 'موقع العنوان المحفوظ غير متاح للشحن. يرجى اختيار عنوان جديد.',
      'CHECKOUT_SAVED_CITY_INVALID': 'المدينة في العنوان المحفوظ غير متاحة للشحن. يرجى اختيار مدينة جديدة.',
      'CHECKOUT_LOADING_DELIVERY': 'جارٍ تحميل خيارات التوصيل...',
      'CHECKOUT_DELIVERY': 'التوصيل',
      'CHECKOUT_LEGAL_PREFIX': 'بإتمام طلبك، فإنك توافق على',
      'CHECKOUT_TERMS': 'شروط الخدمة',
      'CHECKOUT_LEGAL_AND': 'و',
      'CHECKOUT_STEP_PAYMENT': 'الدفع',
      'CHECKOUT_STEP_PAYMENT_SUB': 'ادفع بأمان باستخدام بطاقتك الائتمانية أو البنكية',
      'CHECKOUT_NEXT': 'متابعة',
      'CHECKOUT_STEP_BACK': 'رجوع',
      'CHECKOUT_EDIT': 'تعديل',
      'CHECKOUT_REVIEW_NOTE': 'طلبك جاهز. راجع التفاصيل ثم أكد طلبك بأمان.',
      'CHECKOUT_LOADING_PAYMENT': 'جارٍ تحميل نموذج الدفع الآمن...',
      'CHECKOUT_PAYMENT_SECURE': 'بيانات بطاقتك مشفرة وتتم معالجتها بأمان.',

      // Order Tracking
      'ORDER_TRACKING_TITLE': 'تتبع الطلب',
      'ORDER_STEP_PLACED': 'تم استلام الطلب',
      'ORDER_STEP_PAYMENT': 'تم تأكيد الدفع',
      'ORDER_STEP_SHIPPED': 'تم الشحن',
      'ORDER_STEP_DELIVERED': 'تم التوصيل',
      'ORDER_BACK_LIST': 'العودة للطلبات',
      'ORDER_LOADING': 'جارٍ تحميل تفاصيل الطلب...',
      'ORDER_ERROR': 'تعذر تحميل تفاصيل الطلب.',
      'ORDER_SHIPPING_ADDRESS': 'عنوان الشحن',
      'ORDER_SUBTOTAL': 'المجموع الفرعي',
      'ORDER_DELIVERY': 'التوصيل',
      'ORDER_TOTAL': 'الإجمالي',
      'ORDER_QR_TITLE': 'امسح لمتابعة هذا الطلب',
      'ORDER_QR_ALT': 'رمز QR لمتابعة الطلب',
      'ORDER_QR_HINT': 'امسح الرمز بكاميرا هاتفك لفتح صفحة متابعة الطلب.',
      'ORDER_QTY': 'الكمية',

      // Auth
      'AUTH_WELCOME_BACK': 'مرحباً بعودتك',
      'AUTH_LOGIN_SUB': 'يرجى إدخال بياناتك للدخول إلى حسابك',
      'AUTH_CREATE_ACC': 'إنشاء حساب جديد',
      'AUTH_REGISTER_SUB': 'انضم إلى Eco للاستمتاع بتجربة تسوق سلسة ومكافآت حصرية',
      'AUTH_NAME': 'الاسم بالكامل / اسم المستخدم',
      'AUTH_EMAIL': 'البريد الإلكتروني',
      'AUTH_PASSWORD': 'كلمة المرور',
      'AUTH_FORGOT_PASS': 'نسيت كلمة المرور؟',
      'AUTH_SIGN_IN': 'تسجيل الدخول',
      'AUTH_SIGNING_IN': 'جاري الدخول...',
      'AUTH_CREATING_ACC': 'جاري إنشاء الحساب...',
      'AUTH_NO_ACC': 'ليس لديك حساب؟',
      'AUTH_HAVE_ACC': 'لديك حساب بالفعل؟',
      'AUTH_REGISTER_LINK': 'أنشئ حساباً جديداً',
      'AUTH_LOGIN_LINK': 'تسجيل الدخول',
      'AUTH_VALID_EMAIL': 'يرجى إدخال بريد إلكتروني صحيح.',
      'AUTH_PASSWORD_PLACEHOLDER': 'أدخل كلمة المرور',
      'AUTH_SHOW_PASSWORD': 'إظهار كلمة المرور',
      'AUTH_HIDE_PASSWORD': 'إخفاء كلمة المرور',
      'AUTH_PASSWORD_REQUIRED': 'كلمة المرور مطلوبة.',
      'AUTH_NAME_PLACEHOLDER': 'مثال: محمد أحمد',
      'AUTH_NAME_ERROR': 'يجب أن يتكون اسم المستخدم من 3 أحرف على الأقل.',
      'AUTH_PASSWORD_MIN': '6 أحرف على الأقل',
      'AUTH_PASSWORD_MIN_ERROR': 'يجب أن تتكون كلمة المرور من 6 أحرف على الأقل.',
      'AUTH_TOAST_GOOGLE_NOT_CONFIGURED': 'تسجيل الدخول عبر Google غير مُعد حالياً.',
      'AUTH_TOAST_GOOGLE_ERROR': 'تعذر تسجيل الدخول عبر Google. يرجى المحاولة مرة أخرى.',
      'AUTH_TOAST_GOOGLE_TITLE': 'Google',
      'AUTH_TOAST_EMAIL_NOT_CONFIRMED': 'يرجى تأكيد بريدك الإلكتروني قبل تسجيل الدخول.',
      'AUTH_TOAST_EMAIL_NOT_CONFIRMED_TITLE': 'البريد الإلكتروني غير مؤكد',
      'AUTH_TOAST_LOGIN_SUCCESS': 'مرحباً بعودتك!',
      'AUTH_TOAST_LOGIN_FAILED': 'فشل تسجيل الدخول',
      'AUTH_TOAST_SESSION_ERROR': 'تم تسجيل الدخول، ولكن تعذر تحميل الجلسة. يرجى المحاولة مرة أخرى.',
      'AUTH_TOAST_INVALID_CREDENTIALS': 'البريد الإلكتروني أو كلمة المرور غير صحيحة.',
      'AUTH_RECOVERY_EYEBROW': 'استعادة الحساب',
      'AUTH_RECOVERY_TITLE': 'إعادة تعيين كلمة المرور',
      'AUTH_RECOVERY_SUB': 'أدخل البريد الإلكتروني المرتبط بحسابك في Eco وسنرسل لك رابط استعادة كلمة المرور.',
      'AUTH_RECOVERY_EMAIL': 'البريد الإلكتروني',
      'AUTH_RECOVERY_SEND': 'إرسال رابط الاستعادة',
      'AUTH_RECOVERY_SENDING': 'جارٍ إرسال الرابط...',
      'AUTH_RECOVERY_RETURN': 'العودة لتسجيل الدخول',
      'AUTH_RECOVERY_CHECK_INBOX': 'تحقق من بريدك الإلكتروني',
      'AUTH_RECOVERY_SENT_TITLE': 'تم إرسال التعليمات',
      'AUTH_RECOVERY_SENT_MESSAGE': 'إذا كان هناك حساب مرتبط بهذا البريد الإلكتروني، فقد أرسلنا تعليمات إعادة تعيين كلمة المرور. تحقق من البريد الوارد ومجلد الرسائل غير المرغوب فيها.',
      'AUTH_RECOVERY_INVALID_EMAIL': 'يرجى إدخال بريد إلكتروني صحيح.',
      'ADMIN_SHIPPING_PRICE': 'سعر الشحن',
      'ADMIN_DELIVERY_DAYS': 'مدة التوصيل بالأيام',
      'ADMIN_SHIPPING_AVAILABLE': 'الشحن متاح',
      'ADMIN_SHIPPING_UNAVAILABLE': 'الشحن غير متاح',
      'ADMIN_SAVE_CITY': 'حفظ المدينة',
      'ADMIN_EDIT': 'تعديل',

      // Footer
      'FOOTER_SLOGAN': 'منتجات مختارة بعناية للحياة العصرية.',
      'FOOTER_SHOP': 'المتجر',
      'FOOTER_SUPPORT': 'الدعم والمساعدة',
      'FOOTER_COMPANY': 'الشركة',
      'FOOTER_RIGHTS': 'جميع الحقوق محفوظة.',
      'FOOTER_CRAFTED': 'صُنع بعناية وإتقان',
      'FOOTER_ALL_PRODUCTS': 'كل المنتجات',
      'FOOTER_NEW_ARRIVALS': 'وصل حديثاً',
      'FOOTER_SHIPPING': 'الشحن والتوصيل',
      'FOOTER_RETURNS': 'الاستبدال والاسترجاع',
      'FOOTER_CAREERS': 'الوظائف',
      'FOOTER_PRIVACY': 'سياسة الخصوصية'
      ,'FOOTER_CONTACT': 'تواصل معنا'
      ,'FOOTER_HOURS': 'السبت - الخميس، ٩ صباحاً - ٩ مساءً'
      ,'FOOTER_FEATURE_QUALITY': 'منتجات عالية الجودة'
      ,'FOOTER_FEATURE_QUALITY_SUB': 'مختارة بعناية من أجلك'
      ,'FOOTER_FEATURE_NATURAL': 'اختيارات موثوقة'
      ,'FOOTER_FEATURE_NATURAL_SUB': 'من مصادر موثوقة'
      ,'FOOTER_FEATURE_DELIVERY': 'توصيل سريع وآمن'
      ,'FOOTER_FEATURE_DELIVERY_SUB': 'لباب بيتك'
      ,'FOOTER_PAYMENT_METHODS': 'طرق الدفع'
      ,'FOOTER_PAYMENT_SECURE': 'دفع آمن وموثوق'
    }
  };

  constructor(
    @Inject(PLATFORM_ID) private platformId: object,
    private readonly http: HttpClient
  ) {
    this.initLanguage();
  }

  private initLanguage(): void {
    if (!isPlatformBrowser(this.platformId)) return;
    const saved = localStorage.getItem(this.storageKey) as Language;
    if (saved && this.availableLanguages().includes(saved)) {
      this.setLanguage(saved);
    } else {
      const browserLang = navigator.language?.startsWith('ar') ? 'ar' : 'en';
      this.setLanguage(browserLang);
    }
    this.loadStaticPack('en');
    this.loadStaticPack('ar');
  }

  setLanguage(lang: Language): void {
    const normalized = lang.trim().toLowerCase();
    if (!normalized) return;
    if (!this.availableLanguages().includes(normalized)) return;
    this.currentLang.set(normalized);
    if (isPlatformBrowser(this.platformId)) {
      localStorage.setItem(this.storageKey, normalized);
      document.documentElement.lang = normalized;
      document.documentElement.dir = normalized === 'ar' ? 'rtl' : 'ltr';
      if (normalized === 'ar') {
        document.body.classList.add('rtl-mode');
      } else {
        document.body.classList.remove('rtl-mode');
      }
    }
  }

  toggleLanguage(): void {
    this.setLanguage(this.currentLang() === 'en' ? 'ar' : 'en');
  }

  private loadStaticPack(lang: string): void {
    if (this.loadedTranslations[lang]) return;
    this.http.get<Record<string, string>>(`/i18n/${lang}.json`).subscribe({
      next: pack => {
        this.loadedTranslations[lang] = pack;
      },
      error: () => undefined,
    });
  }

  t(key: string, params?: Record<string, string | number>): string {
    const lang = this.currentLang();
    let text = this.loadedTranslations[lang]?.[key]
      || this.translations[lang]?.[key]
      || this.loadedTranslations['en']?.[key]
      || this.translations['en']?.[key]
      || key;
    if (params) {
      Object.keys(params).forEach(p => {
        text = text.replace(`{${p}}`, String(params[p]));
      });
    }
    return text;
  }

  /** Localizes display values returned by the API when a translated value is known. */
  value(text: string | null | undefined): string {
    if (!text || this.currentLang() === 'en') return text ?? '';

    const arabicValues: Record<string, string> = {
      'Electronics': 'إلكترونيات',
      'Clothing': 'ملابس',
      'Books': 'كتب'
    };

    return arabicValues[text] ?? text;
  }
}
